const messagesCn = {
	g_website: 'NT',
	g_login: '登录',
	g_register: '注册',
	g_more: '更多',
	g_more_t: '更多>>',
	g_password: '密码',
	g_sendCode: '发送验证码',
	g_sending: '正在发送',
	g_sendSuccess: '发送成功',
	g_enter: '确定',
	g_confirm: '确定',
	g_cancel: '取消',
	g_default: '默认',
	g_buy: '买',
	g_buyIn: '买入',
	g_sell: '卖',
	g_sellOut: '卖出',
	g_time: '时间',
	g_status: '状态',
	g_price: '价格',
	g_quantity: '数量',
	g_limited: '限量',
	g_valuation: '估值',
	g_position: '方向',
	g_decimal: '位',
	g_record: '记录',
	g_loading: '加载中',
	g_consume: '消耗',
	g_mark: '备注',
	g_quota: '额度',
	g_buyNow: '抢购',
	g_period: '期数',
	g_search: '搜索',
	g_rechange: '充币',
	g_withdrawal: '提币',
	g_exchange: '兑换',
	g_coinType: '币种',
	g_canUse: '可用',
	g_freeze: '冻结',
	g_amount: '折合',
	g_total: '总量',
	g_tradeAmount: '交易额',
	g_waitRelease: '待释放',
	g_burnFreeze: '烧伤冻结',
	g_doneRelease: '已释放',
	g_dividend: '分红',
	g_resubmit: '重新提交',
	g_phone: '手机号',
	g_name: '姓名',
	g_idCard: '身份证',
	g_nextStep: '下一步',
	g_copy: '复制',
	g_share: '分享',
	g_invite: '邀请',
	g_coinLength: '币种数量',
	g_no: '否',
	g_yes: '是',
	g_username: '账户名',
	g_showPayType: '展示该付款方式',
	g_save: '保存',
	g_setting: '设置',
	g_chooseCoinType: '选择币种',
	g_linkType: '链类型',
	g_rechangeAddress: '充币地址',
	g_withdrawalAddress: '提币地址',
	g_copy: '复制',
	g_send: '发送',
	g_hello: '你好',
	g_code: '验证码',
	g_user: '账户',
	g_prompt: '提示',
	g_rechange_quantity: '充币数量',
	g_rechange_address: '充币地址',
	g_rechange_status: '充币状态',
	g_transfer: '转账',
	g_deposit: '存入',
	g_deposit_record: '存入记录',
	g_level: '等级',
	g_performance: '业绩',
	g_mutual_transfer: '兑换',
	g_apply: '申请',
	g_coming_soon: '数据对接中，敬请期待',
	g_recipient: '接收者',
	g_sender: '发送人',
	g_obtain: '收获',
	g_type: '类型',
	g_all: '全部',
	g_available_balance: '可用余额',
	g_add: '添加',
	g_noopen: '未开放',
	g_atLast: '到底了',
	g_fees: '手续费',
	g_coinAddress: '区块链交易',
	g_sumbitSuccess: '提交成功',
	g_modify: '修改',
	g_modifying: '修改中',
	g_modifySuccess: '修改成功',
	g_enterBind: '确认绑定',
	g_binding: '绑定中',
	g_bindSuccess: '绑定成功',
	g_close: '关闭',
	g_actual: '实际成交',
	g_limitOrder: '限价委托',
	g_limit: '限价',
	g_marketOrder: '市价委托',
	g_market: '市价',
	g_digits_4: '4位',
	g_digits_3: '3位',
	g_digits_2: '2位',
	g_revoke: '撤单',
	g_guarantee: '保证金',
	g_noData: '暂无数据',
	g_orders: '单',
	g_tradeRate: '交易率',
	g_buyQuantity: '购买数量',
	g_sellQuantity: '出售数量',
	g_totalMoney: '总金额',
	g_service_privacy: '服务协议',
	g_policy_privacy: '隐私政策',
	g_project_introdution: '项目介绍',
	g_version_diary: '版本日志',
	g_current_p: '当前版本: ',
	g_about_we: '关于我们',
	g_account_manage: '账户管理',
	g_tradepassword: '交易密码',
	g_loginpassword: '登录密码',
	g_is_bottom: '到底啦',
	g_people: '人',
	g_submit: '提交',
	g_download: '下载',
	g_time_h:'时',
	g_time_m:'分',
	g_time_s:'秒',

	// 关于
	about_info: 'HBA利用区块链技术构建包括匿名网络通信、算力共享、存储空间共享、带宽共享、信誉共享(信用担保)等各种应用，与各类服务提供商、应用提供商合作，构建公有链、联盟链和私有链应用系统，从而将HBA应用到各类实际应用场景中。',
	about_policy:'隐私政策',
	about_policy_1:'1 一般：HBA及其附属机构（以下简称“HBA”，“我们”）致力于保护和尊重您的隐私。',
	about_policy_2:'本隐私政策管理我们收集，处理和使用您的个人信息。我们将“个人信息”定义为个人识别信息，例如您的姓名，地址，电子邮件地址，交易等。',
	about_policy_3:'本隐私政策的目的是通知您：',
	about_policy_4:'1.1 我们可能收集的关于您的个人信息以及如何使用这些信息；',
	about_policy_5:'1.2 我们使用有关IP地址和我们使用Cookie的信息；',
	about_policy_6:'1.3 将个人信息披露给第三方；',
	about_policy_7:'1.4 您更正，更新和删除您的个人信息的能力; 和我们制定的安全措 施可以防止我们控制的个人信息的丢失，滥用或篡改；',
	about_policy_8:'2 收集和使用个人信息：如果您使用本网站，开立账户以使用平台或在平台上执行任何交易，我们可能会收集您的个人信息。我们收集的个人信息类型可能包括：',
	about_policy_9:'2.1 你的名字',
	about_policy_10:'2.2 你的地址。',
	about_policy_11:'2.3 你的电话号码。',
	about_policy_12:'2.4 你的邮件地址。',
	about_policy_13:'2.5 你的账号信息。',
	about_policy_14:'2.6 你的交易',
	about_policy_15:'我们可能会将您的个人信息用于以下目的：',
	about_policy_16:'2.a 允许您在平台上开立和操作账户。',
	about_policy_17:'2.b 使您能够在平台上完成交易。',
	about_policy_18:'2.c 如果您联系我们，我们将回复您的问题。',
	about_policy_19:'2.d 分析我们网站的使用情况。',
	about_policy_20:'2.e 根据监管目的的要求',
	about_policy_21:'2.f 向您提供有关您自己和第三方可能感兴趣的产品和促销活动的 信息，但前提是您已明确同意接收此类信息。',
	about_policy_22:'2.g 进行市场调研，例如调查用户对我们的表现等方面的需求和意见。',
	about_policy_23:'3 支付卡详细信息传输的安全功能和策略：HBA完全符合PCI DSS LEVEL 2. 您可以在此查看信息。此外，所有敏感用户的数据都受到多层加密和多层安全保护，以防止未经授权的访问。',
	about_policy_24:'4 IP地址：我们可能会搜集有关您的计算机信息（包括可用的IP地址，操作系统和浏览器类型），以进行系统管理，并向我们的广告客户报告汇总信息。这是关于我们用户的浏览行为和模式的统计数据，并没有标识任何个人。',
	about_policy_25:'5 Cookies：我们使用从Cookie收集的信息来评估我们网站的有效性，分析趋势并管理平台。从Cookies收集的信息使我们能够确定我们网站的哪些部分访问量最大，以及访问者访问我们的网站时遇到的困难。',
	about_policy_26:'有了这些知识，我们可以通过识别和提供更多最想要的功能和信息，以及解决访问困难，改善您在平台上的体验质量。我们也使用Cookies和/或称为网页错误或清晰的gif技术，通常存储在电子邮件中，以帮助我们确认您的收据，我们使用第三方服务提供商，协助我们更好地了解我们网站的使用情况。我们的服务提供商会将Cookies放置在您计算机的硬盘上，并会收到我们选择的信息，这些信息将向我们介绍访问者在我们网站的浏览方式，浏览的产品以及一般交易信息。我们的服务提供商分析这些信息，并向我们提供汇总报告。我们服务提供商提供的信息和分析将用于帮助我们更好地了解访问者在我们网站的兴趣以及如何更好地为这些兴趣服务。我们的服务提供商所收集的信息可能与我们在使用平台时收集的关于您的信息相关联，并与之相结合。通过使用我们的网站，您同意我们可以使用Cookies来达到上述目的。',
	about_policy_27:'6 个人信息披露：我们将个人信息用于您向我们提供此类信息时指示的用途，和/或用于本隐私政策中规定的目的和/或法律另行允许的用途。',
	about_policy_28:'为了这些有限的目的，我们可能会将您提供给我们的个人信息提供给我们的关联公司，代理商，代表，值得信赖的服务提供商和承包商。',
	about_policy_29:'在合并，剥离或其他公司重组的情况下，我们也可能与金融机构，保险公司或其他公司共享用户的个人信息。',
	about_policy_30:'根据法律的要求，我们也可能会将用户的个人信息与执法机构或监管机构共享。除非法律另有要求或许可，否则任何接收或访问个人信息的第三方都必须要求我们保护此类个人信息，并仅用于为您或HBA执行服务。',
	about_policy_31:'我们将确保任何此类第三方知道我们在本隐私政策下的义务，并且我们将与第三方订立合同，而且这些第三方受其条款约束不低于保护披露给他们的任何个人信息的义务，您根据本隐私政策或根据适用的数据保护法强加于我们。',
	about_policy_32:'7 更正、更新、删除个人信息：你有权访问您的个人信息，并通过发送电子邮件给我们：vcakefu@yeah.net，要求更正，更新和屏蔽不准确的数据。您也可以通过发送电子邮件给我们要求删除或销毁账户，HBA只会在不违反法律和监管义务的情况下采取行动。根据您的书面要求，我们会通知您我们所持有的与您有关的个人信息以及您的个人信息的使用和一般性披露。我们也会给你一份我们保留的个人信息副本，访问您的个人信息可能会收取最低的费用。',
	about_policy_33:'8 安全：我们已实施安全措施，以确保您的个人信息的机密性，并保护您的个人信息免受丢失，误用，篡改或破坏。只有HBA授权的人员才能访问您的个人信息，这些人员必须将这些信息视为机密信息。现行的安全措施将不时根据法律的技术发展进行审查。',
	about_policy_34:'9 保留个人信息：考虑到本隐私政策和我们自己的法律和法规要求中所述的目的，只要我们有必要这样做，我们就会保留您的个人信息。根据我们的记录保存义务，我们将保留账户和个人信息，至少在用户关闭后的五年内。',
	about_policy_35:'10 链接：本网站可能存在与第三方提供的其他网站和资源的链接。本隐私政策仅适用于我们的网站。访问这些第三方网站或来源需要您离开我们的网站。我们不控制这些第三方网站或其中包含的任何内容，您同意我们对任何第三方网站（包括但不限于其内容，政策，失败，促销，产品）概不负责、服务或行为由这些网站所引起的任何损害、损失、失败等问题。我们鼓励您访问的每个网站的所有政策，规则，条款和规定，包括隐私政策。',
	about_policy_36:'11 营销：您有权要求我们不要出于营销目的处理您的个人信息。您可以通过查看我们用于收集您的个人信息的表单上的某些框来行驶您的权利，以阻止此类处理。',
	about_policy_37:'12 变化：我们的网站政策，内容，信息，促销，披露，免责声明和功能可以在任何时候进行修改，更新或补充，无需事先通知，由HBA独自决定。如果我们更改本隐私政策，将采取措施通过我们网站上发布修改后的隐私政策。',
	about_policy_38:'如果您对我们的隐私政策有任何疑问，请与我们联系，电子邮件地址如下：vcakefu@yeah.net',
	
	about_agreement:'用户协议',
	about_agreement_1:'本协议始定于2020年9月30日',
	about_agreement_2:'最终解析权归属FILEX运营方平台',
	about_agreement_3:'欢迎阅读FILEX平台注册协议（以下简称“本协议”）。',
	about_agreement_4:'特别提醒：您成为平台用户前，必须阅读、同意并接受本协议中所含的所有条款和条件，包括以下明示载明的及因被提及而纳入的文件、条款和条件。',
	about_agreement_5:'您申请注册为平台用户，表明您已经充分阅读、理解并无任何附加条件地接受了本协议中含有的所有条款和条件，包括本协议及其所援引的其他文件的条款内容及其法律含义。',
	about_agreement_6:'您只要复选注册页面中的《我已阅读并同意FILEX平台用户注册协议》并按照本网站规定的注册程序成功注册为用户，您的行为既表示同意并签署了本服务协议。本服务协议不涉及您与本网站的其他用户之间因网上交易而产生的法律关系及法律纠纷。',
	about_agreement_7:'重要提示： 我们在此特别提醒您：',
	about_agreement_8:'1.数字资产本身不由任何金融机构或公司或本网站发行；',
	about_agreement_9:'2.数字资产市场是全新的、未经确认的，而且可能不会增长；',
	about_agreement_10:'3.数字资产主要由投机者大量使用，零售和商业市场使用相对较少，数字资产交易存在极高风险，其全天不间断交易，没有涨跌限制，价格容易受庄家、全球政府政策的影响而大幅波动；',
	about_agreement_11:'4.因各国法律、法规和规范性文件的制定或者修改，数字资产交易随时可能被暂停或被禁止。',
	about_agreement_12:'数字资产交易有极高风险，并不适合绝大部分人士。您了解和理解此投资有可能导致部分损失或全部损失，所以您应该以能承受的损失程度来决定投资的金额。您了解和理解数字资产会产生衍生风险，所以如有任何疑问，建议先寻求理财顾问的协助。此外，除了上述提及过的风险以外，还会有未能预测的风险存在。您应慎重考虑并用清晰的判断能力去评估自己的财政状况及上述各项风险而作出任何买卖数字资产的决定，并承担由此产生的全部损失，我们对此不承担任何责任。',
	about_agreement_13:'一、用户资格',
	about_agreement_14:'1.1 您应当具有完全民事权利能力和民事行为能力，并能够独立承担民事责任。',
	about_agreement_15:'1.2 不属于平台提供用户服务的以下人群：',
	about_agreement_16:'(1) 未满18周岁和超过70周岁的自然人；',
	about_agreement_17:'(2) 没有非保本类金融产品投资经历或不熟悉互联网的投资人。',
	about_agreement_18:'二、用户账户管理',
	about_agreement_19:'2.1 您在平台的注册账户仅限本人使用，不得出借或转让。请妥善保管用户名、密码等账户信息，因其泄露或被盗用所产生的任何损失，都将由您自己承担。',
	about_agreement_20:'2.2 凡以您的注册账户登录实施的一切行为均视为您本人的行为，所产生的法律后果由您承担。您如发现存在账户被盗用或其他非法使用的情形，应立即以有效方式通知平台冻结资金，保障您的财产安全；同时，请您理解平台对上述情形采取行动需要合理期限，在此之前，平台对任何非法使用行为所导致的损失不承担任何责任。',
	about_agreement_21:'2.3 发生下列情形之一的，平台有权基于独立判断，不经通知而单方先行暂停、中断或终止向您提供相关服务，并不对因此产生的损失承担责任：',
	about_agreement_22:'（1）平台认为您提供的个人资料不具有真实性、有效性或完整性，包括但不限于盗用他人证件信息注册、认证信息不匹配等；',
	about_agreement_23:'（2）平台认为存在异常交易或交易可能涉嫌洗钱、套现、传销、恐怖活动等违法行为时；',
	about_agreement_24:'（3）平台发现您使用非法或不正当的技术手段进行危害交易安全或影响公平交易的行为，包括但不限于篡改交易数据、窃取客户信息、窃取交易数据、通过平台攻击其他用户等；',
	about_agreement_25:'（4）平台认为您的账户存在被盗用、冒用或其他风险时；',
	about_agreement_26:'（5）平台认为您已经违反本协议中规定的各类规则及精神；',
	about_agreement_27:'（6）平台为保障交易安全和公平而需要采取措施的其他情形。',
	about_agreement_28:'2.4 您同意并授权，当平台因战略调整需要系统升级改造、产品功能模块拆分或合并、运营主体变更及其他任何必要的调整时，可以将与您相关的数据（包括但不限于用户注册信息、用户个人信息、交易数据及其他相关资料）同步更新到调整后的门户网站、APP、客户端或其他关联应用上。您在使用此类应用时，可以用原有账户进行登录并操作。',
	about_agreement_30:'您在此确认并授权：在您通过平台进行交易过程中向平台提交的申请或指令，由平台向存管银行发出。',
	about_agreement_31:'三、服务和费用',
	about_agreement_32:'3.1 服务',
	about_agreement_33:'3.1.1 FILEX交易平台作为金融科技服务平台，为用户提供综合金融信息服务。',
	about_agreement_34:'3.1.2 请您自行判断、确认平台上相关项目的风险，平台不对您及参与各方的交易承担任何责任。',
	about_agreement_35:'3.1.3 第三方责任在任何情况下，对于您使用平台服务过程中涉及由银行等第三方提供服务的责任由该第三方承担，平台不承担责任。平台不承担责任的情形包括但不限于：',
	about_agreement_36:'（1）第三方未按照您或平台指令进行操作引起的损失或责任；',
	about_agreement_37:'（2）第三方原因导致资金未及时到账及与之相关的损失或责任；',
	about_agreement_38:'（3）第三方对交易限额或次数等的限制导致的损失或责任。',
	about_agreement_39:'3.2 费用',
	about_agreement_40:'3.2.1 平台暂不对使用平台用户收取费用。',
	about_agreement_41:'3.2.2 尽管有前款约定，但平台保留在法律规定范围内按照运营战略自行发布通知调整收费标准及',
	about_agreement_42:'收费方式的权利。通知发布后，如您继续使用平台服务，视为您对该等通知内容予以认可并接受。',
	about_agreement_43:'3.3 其他',
	about_agreement_44:'3.3.1 您使用平台所提供服务过程中的其他支出（包括但不限于网络使用费、通信费、资料快递费等），由您自行承担。',
	about_agreement_45:'3.3.2 您因使用平台所提供服务完成的交易而取得的收入，应当由您按照所适用法律规定承担相应的税费。',
	about_agreement_46:'四、您的资料',
	about_agreement_47:'4.1 您的资料包括：您在注册或登录过程中、在任何公共信息区域（包括留言栏或反馈区）或通过任何电邮形式或手机短信向平台或其他用户提供的任何资料。您对您的资料负全责，平台仅作为您在网上分发及公布您的资料的渠道。',
	about_agreement_48:'4.2 您应根据平台的要求提供真实、有效及完整的资料。资料不得：具有欺诈性、虚假、不准确或具误导性；侵犯任何第三方著作权、专利权、商标权、商业秘密或其他专有权利或发表权或隐私权；违反任何适用的法律或法规；有侮辱或者诽谤他人，侵害他人合法权益的内容；有淫秽、色情、赌博、暴力、凶杀、恐怖或者教唆犯罪的内容；包含可能破坏、改变、删除、不利影响、秘密截取、未经授权而接触或征用任何系统、数据或个人资料的任何病毒、特洛依木马、蠕虫、定时炸弹、删除蝇、复活节彩蛋、间谍软件或其他电脑程序；直接或间接链接至您无权链接或列入的任何网址或者内容。',
	about_agreement_49:'4.3 为使平台能够使用您向平台提交的资料，使平台不违反您可能在该资料中拥有的任何权利之目的，您应同意向平台授予非独占、全球性、永久、不可撤销、免使用费、可分许可（通过多层许可的方式）的权利，以行使您在您的资料中（在任何已知或目前为未知媒体中）享有的与您的资料有关的相关权利。平台将根据隐私条款使用您的资料。',
	about_agreement_50:'4.4 您有义务维持并更新您的资料，确保其为真实、有效及完整。若您提供任何错误、虚假、过时或不完整的资料，或者平台依其独立判断怀疑资料为错误、虚假、过时或不完整，平台有权拒绝您使用平台服务的部分或全部功能或采取其他处理措施。在此情况下，平台不承担任何责任，并且您同意负担因此所产生的直接或间接的任何支出或损失。',
	about_agreement_51:'4.5 如因您未及时更新基本资料，导致平台服务无法提供或提供时发生任何错误，您不得将此作为取消交易的理由，平台亦不承担任何责任，所有后果应由您承担。',
	about_agreement_52:'4.6 除本协议以外，您应同时遵守平台不时发布及更新的全部规则，包括但不限于公告、产品流程说明、平台项目说明、风险提示等。',
	about_agreement_53:'4.7您同意平台应法律法规、行业监管等要求之目的，将您的相关信息在平台或其他渠道进行披露。',
	about_agreement_54:'五、进入和干扰',
	about_agreement_55:'5.1 未经平台明示或者书面准许，您不能为了任何目的使用任何机器人、蜘蛛软件、刷屏软件或其他自动方式进入网站。',
	about_agreement_56:'5.2 此外，您同意您将不会：',
	about_agreement_57:'（1）进行任何对平台内部结构造成或可能造成（按平台自行酌情确定）不合理或不合比例的重大负荷的行为；',
	about_agreement_58:'（2）未经平台和适当第三方（如适用）事先明示书面准许，对网站的任何内容（除您的资料以外）制作拷贝、进行复制、修改、制作衍生作品、分发或公开展示；',
	about_agreement_59:'（3）干扰或试图干扰网站的正常工作或网站上进行的任何活动；',
	about_agreement_60:'（4）越过平台可能用于防止或限制进入网站的机器人排除探头或其他形式。',
	about_agreement_70:'六、欺诈',
	about_agreement_71:'您在使用平台服务的过程中不得从事欺诈行为。若平台有合理理由怀疑您参与了与平台有关的欺诈活动时，平台可单方酌情决定采取中止或终止您的账户等处理措施，并不对因此给您造成的损失承担任何责任。',
	about_agreement_72:'七、违约',
	about_agreement_73:'在不限制其它救济的前提下，如发生以下情形，平台可能限制您的活动，发出有关您的行为的警告、暂时中止、无限期地中止或终止您的用户资格及拒绝向您提供服务：',
	about_agreement_74:'7.1 您违反本协议或纳入本协议的文件；',
	about_agreement_75:'7.2 平台无法核验您向平台提供的资料或信息；',
	about_agreement_76:'7.3 您的行为可能对平台其他用户、平台合作方或平台造成损失或法律责任。',
	about_agreement_77:'八、信息收集、使用、共享授权及保护条款',
	about_agreement_78:'8.1 收集您的信息',
	about_agreement_79:'8.1.1 为了更好地向您提供平台服务，您同意并授权本公司通过以下途径获取您的信息：',
	about_agreement_80:'8.1.1.1 收集您留存在本公司的关联公司处的信息；',
	about_agreement_81:'8.1.1.2 收集您留存在本公司合作伙伴（包括但不限于证券机构、保险机构、银行、基金公司、支付机构、合作分站等，下同）处的信息；',
	about_agreement_82:'8.1.1.3 向行政机关、司法机关、协会组织、第三方行业媒体等机构查询、打印、留存您的信息；',
	about_agreement_83:'8.1.1.4 向合法留存您的信息的自然人、法人或其他组织收集您的信息。',
	about_agreement_84:'8.1.2 您同意并授权本公司收集您的信息包括但不限于：',
	about_agreement_85:'8.1.2.1 您的身份信息，包括但不限于姓名/名称、证件号码、证件类型、住所地、电话号码、平台账户或合作伙伴账户认证信息以及其他身份信息；',
	about_agreement_86:'8.1.2.2 您在申请、使用平台服务时所提供的以及形成的任何数据和信息；',
	about_agreement_87:'8.1.2.3 您在本公司关联公司和合作伙伴处留存以及形成的任何数据和信息，包括但不限于您的平台账户和/或证券账户、银行账户、基金账户信息、您与本公司关联公司或合作伙伴之间存在的任何协议以及您在该等协议项下的履约情况、您在本公司关联公司或合作伙伴平台上的行为数据等；',
	about_agreement_88:'8.1.2.4 您的信用信息，包括但不限于您的征信记录和信用报告；',
	about_agreement_89:'8.1.2.5 您的财产信息，包括但不限于您的店铺/企业经营状况、财税信息、房产信息、车辆信息、基金、保险、股票、信托、债权等投资理财信息和负债信息等；',
	about_agreement_90:'8.1.2.6 您在行政机关、司法机关留存的任何信息，包括但不限于户籍信息/工商信息、诉讼信息、执行信息和违法犯罪信息等；',
	about_agreement_91:'8.1.2.7 与您申请或使用平台服务相关的、您留存的其他自然人、法人或其他组织的相关信息。',
	about_agreement_92:'8.1.3 您同意本公司可以在平台及相关的某些网页上使用诸如“Cookies”的资料收集装置，采取人工或自动追踪手段收集您的信息，并可通过人工或自动程序对您的资料进行分析评价。',
	about_agreement_93:'8.2 使用您的信息  您同意并授权本公司将您的信息用于如下用途：',
	about_agreement_94:'8.2.1 利用整个用户数据库（包括您的信息）创建数据分析模型；',
	about_agreement_95:'8.2.2 比较核对信息的准确性并与第三方进行交叉验证；',
	about_agreement_96:'8.2.3 为使您知晓或了解平台服务情况，通过电子邮件、平台站内信、本公司关联公司或合作伙伴的信息发送渠道、手机短信、传真、微信、QQ或其他方式向您发送产品更新、服务状态等的通知、营销活动及其他商业性电子信息；',
	about_agreement_97:'8.2.4 本公司、本公司关联公司或合作伙伴为了风险防控需要或预防、阻止非法活动；',
	about_agreement_98:'8.2.5 经您许可的或与向您提供服务有关的其他用途。',
	about_agreement_99:'8.3 分享您的信息',
	about_agreement_100:'本公司对您的信息承担保密义务，不会为满足无关第三方的营销目的而将您的信息出售或出租，仅在下列情况之一时才会与第三方共享您的信息：',
	about_agreement_101:'8.3.1 获得您的同意或授权；',
	about_agreement_102:'8.3.2 为了向您提供或推荐本公司关联公司的服务/产品的需要，将您的信息提供给本公司的关联公司使用，您同意本公司的关联公司通过手机短信、邮件、微信、QQ、传真等方式向您发送产品信息、服务状态通知、营销活动或其他商业性电子信息；',
	about_agreement_103:'8.3.3 某些服务/产品或宣传推广活动由本公司或本公司关联公司的合作伙伴提供或由本公司、本公司的关联公司与合作伙伴共同提供（包括但不限于您基于前述背景通过绑定或使用本公司邀请码进行注册或投资的情况），您同意本公司使用或与该合作伙伴共享您的信息；',
	about_agreement_104:'8.3.4 为了建立信用体系，向征信机构发送您的信息，您同意并授权本公司可以将您的不良信息发送征信机构且不再另行通知您；',
	about_agreement_105:'8.3.5 您同意并授权本公司或本公司关联公司、合作伙伴可以在向监管部门等自律机构提供信息、用以解决纠纷或调停等过程中使用或与此类机构共享您的信息。',
	about_agreement_106:'8.3.6 您同意并授权本公司可以在平台系统升级或业务拆分、本公司向关联公司、合作伙伴或其他交易方转让权利或义务的过程中，可以与相关方共享您的信息；',
	about_agreement_107:'8.3.7 提供独立服务且仅要求服务相关的必要信息的供应商，如印刷厂、邮递公司等；',
	about_agreement_108:'8.3.8 法律法规或监管政策规定、有权机关的常规或临时要求、其他为了向您提供产品或服务所需的场景等用途。',
	about_agreement_109:'8.4 您的信息保护',
	about_agreement_110:'本公司重视对用户隐私的保护，将按照法律法规规定采取保密措施予以保护您的信息，但是下列情况除外：',
	about_agreement_111:'8.4.1 法律、法规、政策、监管、行业自律组织等另有要求的；',
	about_agreement_112:'8.4.2 本协议另有约定；',
	about_agreement_113:'8.4.3 本公司之外的第三方原因或不可抗力、意外事件等情况导致您的信息被泄露、盗用、出售或其他非法使用情形的。',
	about_agreement_114:'8.5 本条约定具有独立性，不应本协议及其他条款生效与否或效力变化的影响。',
	about_agreement_115:'九、不保证',
	about_agreement_116:'9.1 平台对于向用户提供的服务不提供任何形式的承诺或保证，无论该等保证或承诺是明示、默示或法定的。',
	about_agreement_117:'9.2 平台上合作单位所提供的服务品质及内容由该合作单位自行负责。',
	about_agreement_118:'9.3 平台不就持续地、不受影响地或安全地接触并接受平台服务作出担保，且平台网站的经营可能受平台无法控制的多种外部因素影响。',
	about_agreement_119:'十、特别声明',
	about_agreement_120:'10.1 平台并不介入您与其他用户之间的交易，对此，您充分理解并认可。',
	about_agreement_121:'10.2 您同意就您自身行为之合法性单独承担责任。您同意，平台和平台的所有关联公司和相关实体对平台用户的行为的合法性及产生的任何结果不承担责任。',
	about_agreement_122:'10.3 您同意并接受本服务条款，视同您同意并接受平台以投放广告或发送短信、彩信和邮件等形式的营销行为。',
	about_agreement_123:'10.4 您使用平台的服务及因此所进行的交易，应当遵守所有适用的国内及国际法律、法令、条例和法规。',
	about_agreement_124:'十一、补偿及责任免除',
	about_agreement_125:'11.1 就任何第三方提出的，由于您违反本协议或纳入本协议的条款和规则或您违反任何法律或侵犯第三方的权利而产生或引起的任一种类和性质的任何索赔、要求、诉讼、损失和损害（包括直接或间接的），无论是已知或未知的（包括合理的律师费），您同意就此对平台和（如适用）平台的母公司、子公司、关联公司、合作伙伴、高级职员、董事、代理人和雇员进行补偿并使其免受损害。',
	about_agreement_126:'11.2 您同意，基于互联网的特殊性，系统可能会因相关状况无法正常运作，从而使您无法使用任何平台服务或受到不利影响，平台就此对您或第三方不负任何责任，前述状况包括但不限于：',
	about_agreement_127:'（1）平台系统停机维护期间；',
	about_agreement_128:'（2）电信设备出现故障不能进行数据传输的；',
	about_agreement_129:'（3）由于黑客攻击、网络供应商技术调整或故障、网站升级、银行方面的问题等原因而造成的本平台服务中断或延迟；',
	about_agreement_130:'（4）因台风、地震、海啸、洪水、停电、战争、恐怖袭击等不可抗力之因素，造成平台系统障碍不能执行业务的。',
	about_agreement_131:'十二、知识产权的保护',
	about_agreement_132:'12.1 平台上所有内容，包括但不限于著作、图片、档案、资讯、资料、平台架构、平台画面的安排、网页设计，均由平台或其他权利人依法拥有其知识产权，包括但不限于商标权、专利权、著作权、商业秘密等。',
	about_agreement_133:'12.2 非经平台或其他权利人书面同意，任何人不得擅自下载、使用、修改、复制、公开传播、改变、散布、发行或公开发表平台程序或内容；不得对平台或对平台的内容进行系统获取以直接或间接创建或编辑文集、汇编、数据库或人名地址录（无论是否通过Robots、Spiders、自动仪器或手工操作）；不得对平台内容进行转售或商业利用；不得收集和利用产品目录、说明和价格；不得用frame或运用frame技巧把平台或其关联公司的商标、标识或其他专有信息（包括图像、文字、网页设计或形式）据为己有；不得以Meta Tags或任何其他"隐藏文本"方式使用平台或其关联公司的名字和商标。',
	about_agreement_134:'十三、无代理关系',
	about_agreement_135:'用户和平台是独立的合同方，本协议无意建立也没有创立任何代理、合伙、合营、雇员与雇主或特许经营关系。平台也不对任何用户及其网上交易行为做出明示或默许的推荐、承诺或担保。上述性质不因任何事由而改变。',
	about_agreement_136:'十四、通知',
	about_agreement_137:'平台对于您的通知及任何其他的协议、告示或其他关于您使用平台账户及服务的通知，您同意平台可通过平台公告、站内信、电子邮件、手机短信、ins、facebook、无线通讯装置等电子方式或邮寄等物理方式进行，该等通知于发送之日视为已送达收件人（如以邮寄方式向您发出通知的，则在该等通知按照您在平台留存的联系地址交邮后的第三个自然日即视为送达）。因不可归责于平台的原因（包括但不限于电子邮件地址、手机号码、联系地址等不准确或无效、信息传输故障等）导致您未在前述通知视为送达之日收到该等通知的，平台不承担任何责任。',
	about_agreement_138:'十五、协议的生效、修改、补充和终止',
	about_agreement_139:'15.1 在本协议履行过程中，平台可根据情况对本协议进行修改。一旦本协议的内容发生变动，将通过平台公告的方式通知您，该等变动自公告发布之日起生效。',
	about_agreement_140:'15.2 若您对于该等修改和补充不予接受的，您应当立即停止使用平台的服务，而平台亦有权终止您的用户资格。如果您继续使用平台服务，则视为您接受平台对本协议所做的修改，并应遵照修改后的协议执行。',
	about_agreement_141:'15.3 本协议在您提交的注册为平台用户的申请获得审核通过时生效。',
	about_agreement_142:'15.4 本协议自您注销您的用户账户的申请被平台审核通过之日，或者平台依据本协议及本协议所纳入或被提及的文件、条款和条件终止您的用户资格之日终止。',
	about_agreement_143:'十六、条款的解释、法律适用及争端解决',
	about_agreement_144:'16.1 本协议及其修订的有效性、履行与本协议及其修订效力有关的所有方面均受美国及其它国际法律国家管辖。',
	about_agreement_145:'16.2 因本协议所引起的您与平台的任何纠纷或争议，首先应友好协商解决，如协商不能解决，均应提交平台所在地有管辖权的法院诉讼解决。',
	about_agreement_146:'16.3 本协议的规定是可分割的，如本协议任何规定被裁定为无效或不可执行，在此情况下，本协议的其他条款仍然完全有效并具有约束力。',
	about_agreement_147:'16.4 平台未就您或其他方的违约采取行动并不等于平台放弃就随后或类似的违约采取行动的权利。',
	about_agreement_148:'16.5 本协议可能会根据国家新政策的调整，和相关法律的完善，对协议进行调整，最终的解释权归属FILEX运营方平台。',

	

	// 账户管理
	account_wallet_addr: '地址：',
	account_wallet_name: '钱包名称',
	account_export_mnemonic: '导出助记词',
	account_export_private_key: '导出私钥',
	account_exit_wallet: '退出钱包',
	account_please_input_wallet_name: '请输入钱包名称',
	account_wallet_is_empty: '钱包名称不能为空',
	account_wallet_length_is_error: '钱包名称设置为10个字以内',
	account_tradepassword_is_error: '交易密码不正确',
	account_export_success: '导出成功',
	account_export_tips_1: '请认真抄写并安全保管，切勿泄露自己的私钥',
	account_export_tips_2: '钱包服务器不保管用户私钥，遗失无法找回',
	account_wallet_address: '钱包地址',
	account_private_key: '私钥',
	account_mnemonic: '助记词',

	// 激活
	active_invite: '邀请激活',
	active_input_other_addr: '请输入对方地址',
	active_other_addr: '对方地址',
	active_must_use: '激活需要消耗',
	active_invite_success: '激活成功',

	// 我的
	mine_yijh: '已激活',
	mine_weijh: '未激活',
	mine_send: '发布交易',
	mine_shequ: '我的社区',
	mine_service: '在线客服',
	mine_action: '操作教程',
	mine_safe: '安全中心',
	mine_language: '语言切换',
	mine_account: '账户管理',
	mine_explorer: '区块浏览器',
	mine_open: '开源地址',
	mine_share: '分享APP',
	mine_version: '版本号',
	
	// 公告
	announcement_title: '公告',
	announcement_title_details: '公告详情',
	
	// 资产
	assets_total: '总账户资产折合',
	assets_button_1: '提币',
	assets_button_2: '充币',
	assets_button_3: '划转',
	assets_tabs_1: '币币',
	assets_tabs_1_total: '币币总资产折合',
	assets_tabs_2: '合约',
	assets_tabs_2_total: '法币总资产折合',
	assets_tabs_3: '矿池',
	assets_tabs_3_total: '矿池总资产折合',
	assets_airdrop_quota: '空投额度: ',
	assets_input: '转入: ',
	assets_out: '转出: ',
	assets_select_trade: '选择币种 ',
	assets_transfer_num: '划转数量',
	assets_can_use: '可用: ',
	
	assets_tabs_5_button_1: '节点权益',
	assets_tabs_5_button_2: '合约返还',
	assets_tabs_5_header_1: '总返还',
	assets_tabs_5_header_2: '已返还',
	assets_detail_record: '财务记录',
	assets_detail_title: '记录详情',
	assets_detail_1: '类型',
	assets_detail_2: '买入',
	assets_detail_3: '状态',
	assets_detail_4: '已完成',
	assets_detail_5: '时间',
	
	// 收款
	collection_title:'NT收款',
	collection_wallet_addr:'钱包地址',
	collection_scan:'扫一扫',
	collection_record_detail:'记录详情',
	collection_out_afil:'转入NT',
	collection_out_addr:'转出地址',
	collection_receive_addr:'接收地址',
	collection_finish:'销毁',
	collection_kuaigao:'块高',
	collection_type_1:'转账',
	collection_type_2:'激活账号',
	collection_type_3:'挖矿收益',
	collection_type_4:'提币',
	collection_account_record:'账本记录',
	collection_status_1:'未确认',
	collection_status_2:'已确认',

	// 社区
	shequ_title_1:'激活矿工',
	shequ_title_2:'共享投票',
	shequ_text_1:'激活数量',
	shequ_text_2:'总设备数量',
	shequ_text_3:'矿池等级',
	shequ_text_4:'邀请人数',
	shequ_text_5:'社区人数',
	shequ_text_6:'有效投票数量',
	shequ_text_7:'邀请地址',
	shequ_text_8:'设备数量',
	shequ_text_9:'直推人数',
	shequ_text_10:'团队人数',
	
	// 矿池
	pool_title:'矿池',
	pool_min_chi:'最低持币',
	pool_day_income:'日收益',
	pool_total_income:'累计收益',
	pool_chi_or_tui:'持币/推广算力',
	pool_detail:'矿池详情',
	pool_income:'矿池收益',
	pool_chi_calculate:'持币算力',
	pool_tg_calculate:'推广算力',
	pool_miner_detail:'矿工详情',
	pool_week_income:'最近一周收益',
	pool_chi_rate:'持币收益率',
	pool_tg_total_calculate:'推广总算力',
	pool_chibi:'持币',
	pool_income_record:'收益记录',
	pool_chi_income:'持币收益',
	pool_tg_income:'推广收益',
	
	// 助记词
	mnemonic_i_read:'我已阅读并同意',
	mnemonic_user_agreement:'用户协议',
	mnemonic_create_addr:'创建地址',
	mnemonic_export_addr:'导入地址',
	mnemonic_agree_first:'请先同意用户协议',
	mnemonic_backup_succ:'备份成功',
	mnemonic_create_succ:'创建地址成功',
	mnemonic_save_your:'请妥善保管您的助记词',
	mnemonic_not_forget:'请勿丢失或泄露给他人，以免造成财产损失',
	mnemonic_set_your_name_pwd:'设置您的钱包名称以及交易密码',
	mnemonic_wallet_name:'钱包名称',
	mnemonic_input_wallet_name:'请输入您的钱包名称',
	mnemonic_input_name_length_error:'钱包名称设置为10个字以内',
	mnemonic_input_number_and_word:'请输入数字加字母的密码',
	mnemonic_input_safe_pwd:'请输入安全密码',
	mnemonic_two_pwd_not:'两次密码输入不一致',
	mnemonic_input_tradepassword:'请输入您的交易密码',
	mnemonic_again_tradepassword:'再次确认您的交易密码',
	mnemonic_confirm_pwd:'确认密码',
	mnemonic_test:'验证助记词',
	mnemonic_remember_twelve:'请将您抄下的12个单词按正确顺序选择至上方',
	mnemonic_sort_error:'助记词顺序输入有误',
	mnemonic_write_wallet_and_pwd:'请填写您的钱包名称和交易密码',
	mnemonic_write:'填写助记词',
	mnemonic_input_tips:'请填写您的助记词,英文单词请按空格分隔单词',
	mnemonic_input_your:'请输入您的助记词',
	mnemonic_backup:'备份助记词',
	mnemonic_remember_next:'请按从左至右依次记住下方12个助记词顺序，我们将在下一步验证',
	
	
	// 新闻
	news_detail:'新闻详情',
	
	
	// 公募
	offering_title:'公募',
	offering_quantity:'公募数量',
	offering_single_price:'单价',
	offering_complate:'已完成',
	offering_time:'公募起止时间',
	offering_buy:'认购',
	offering_go_buy:'去认购',
	offering_equals_price:'折后价',
	offering_buy_quantity:'认购数量',
	offering_use_quantity:'可用数量',
	offering_equals:'折合',
	offering_input_your_tradepassword:'请输入您的交易密码',
	offering_not_open:'未开启',
	offering_processing:'进行中',
	offering_finish:'已结束',
	offering_buy_quantity:'请输入认购数量',
	offering_input_tradepassword:'请输入交易密码',
	offering_tradepassword_error:'交易密码不正确',
	offering_buy_success:'认购成功',
	offering_record:'公募记录',
	offering_price:'公募价格',
	offering_money:'公募金额',
	offering_buy_time:'认购时间',
	
	// 其他
	other_title:'其他应用',
	other_text_1:'投票上币',
	other_text_2:'邀请好友',
	other_text_3:'邀请激活',
	other_text_4:'收款',
	other_text_5:'转账',
	other_text_6:'公募',
	other_text_7:'合约',
	other_text_8:'矿池',
	other_text_9:'商城',
	other_text_10:'游戏',
	other_text_11:'教育',
	other_text_12:'慈善',
	other_text_13:'汇兑',
	
	
	// 行情
	quotes_title: '行情',
	quotes_header_1: '名称',
	quotes_header_2: '最新价',
	quotes_header_3: '涨跌幅',
	quotes_24: '24H量',
	
	
	// 安全中心

	safe_title: '安全中心',
	safe_auth: '实名认证',
	safe_tradepassword: '交易密码',
	safe_account: '收款账号',
	safe_toModify: '去修改',
	safe_status_1: '未认证',
	safe_status_2: '认证中',
	safe_status_3: '已认证',
	safe_status_4: '认证失败',
	
	safe_auth_title: '身份认证',
	safe_auth_primary_text_1: '真实姓名',
	safe_auth_primary_text_2: '证件号码',
	safe_auth_primary_text_3: '请上传身份证正面照片',
	safe_auth_primary_text_4: '请上传身份证反面照片',
	safe_auth_primary_text_5: '请上传手持身份证照片',
	safe_auth_primary_btn: '提交审核',
	safe_auth_primary_toast_1: '请输入您的真实姓名',
	safe_auth_primary_toast_2: '请输入您的身份证号',
	safe_auth_primary_toast_3: '请上传身份证正面照',
	safe_auth_primary_toast_4: '请上传身份证反面照',
	safe_auth_primary_toast_5: '请上传手持身份证照',
	safe_auth_primary_toast_6: '提交成功，请等待审核',

	// 收款方式
	safe_skfs_title: '收款方式',
	safe_skfs_bankcard: '银联收款码',
	safe_skfs_alipay: '支付宝收款码',
	safe_skfs_wechat: '微信收款码',
	safe_skfs_yibd: '已绑定',
	safe_skfs_weibd: '未绑定',
	
	safe_confirm: '确认绑定',
	safe_binding: '绑定中',
	safe_bind_succ: '绑定成功',
	
	//银行卡设置
	safe_bank_title: '银联收款账号',
	safe_bank_name: '姓名',
	safe_bank_bankCardId: '银行卡号',
	safe_bank_bankName: '开户行',
	safe_bank_bankAddress: '开户地址',
	safe_bank_toast_1: '请输入真实姓名',
	safe_bank_toast_2: '请输入银行卡号',
	safe_bank_toast_3: '请输入银行卡开户行',
	safe_bank_toast_4: '请输入银行卡开户地址',
	
	//支付宝设置
	safe_alipay_title: '支付宝收款账号',
	safe_alipay_name: '真实姓名',
	safe_alipay_cardId: '支付宝账号',
	safe_alipay_toast_1: '请上传收款码',
	safe_alipay_toast_2: '请输入支付宝账号实名认证的姓名',
	safe_alipay_toast_3: '请输入支付宝账号',
	
	//微信设置
	safe_wechat_title: '微信收款账号',
	safe_wechat_name: '真实姓名',
	safe_wechat_cardId: '微信账号',
	safe_wechat_toast_1: '请上传收款码',
	safe_wechat_toast_2: '请输入微信账号实名认证的姓名',
	safe_wechat_toast_3: '请输入需要绑定的微信收款账号',
	
	// 修改交易密码
	safe_xgjymm_title: '修改交易密码',
	safe_xgjymm_note: '请重新设置您的交易密码',
	safe_xgjymm_text_1: '原交易密码',
	safe_xgjymm_text_2: '新交易密码',
	safe_xgjymm_text_3: '确认新交易密码',
	safe_xgjymm_text_4: '请再次输入新密码',
	safe_xgjymm_text_5: '设置新交易密码',
	safe_xgjymm_text_6: '当前交易密码',
	safe_xgjymm_modify_succ: '修改成功',
	safe_xgjymm_modify_ing: '修改中',
	safe_xgjymm_modify: '修改',
	safe_xgjymm_toast_1: '两次输入的密码不一致',

	// OTC
	otc_title: '交易',
	otc_tabs_1: '我要买',
	otc_tabs_2: '我要卖',
	otc_message_1: '买入后该笔交易24小时内不可提取，其他交易不受影响',
	otc_text_1: '可交易数量',
	otc_text_2: '实付款',
	otc_text_3: '实收款',
	otc_text_4: '下单',
	otc_text_5: '后自动取消',
	otc_text_6: '数量',
	otc_text_7: '限量',
	otc_text_8: '单',
	otc_text_9: '单价',
	otc_text_10: '购买',
	otc_text_11: '出售',
	otc_text_12: '限额',
	otc_loading: '列表拉取中',
	otc_s_cancel: 's后自动取消',
	otc_60_cancel: '60s后自动取消',
	otc_toast_1: '请输入购买数量',
	otc_toast_2: '接单成功',

	otc_record_title: '交易记录',
	otc_record_status_1: '未完成',
	otc_record_status_2: '已完成',
	otc_record_status_3: '已取消',
	otc_record_status_4: '申诉',
	otc_record_buy: '购买',
	otc_record_sell: '出售',
	otc_record_label_1: '总金额',
	otc_record_label_2: '数量',
	otc_record_list_1: '待接单',
	otc_record_list_2: '待支付',
	otc_record_list_3: '待收款',
	otc_record_list_4: '已完成',
	otc_record_list_5: '已取消',
	otc_record_list_6: '申诉中',
	otc_record_list_7: '申诉成功',
	otc_record_list_8: '申诉失败',

	otc_appeal_title: '订单申诉',
	otc_appeal_placeholder: '请输入您的申诉理由',
	otc_appeal_btn: '确定提交',
	otc_appeal_label: '请选择申诉类别',
	otc_appeal_list_1: '买单——用户已付款，但商户不确认收款',
	otc_appeal_list_2: '卖单——未付款时，商户点击已付款',
	otc_appeal_list_3: '卖单——商户已付款，但付款金额错误',
	otc_appeal_toast_1: '请输入您的申诉理由',

	otc_details_lable_1: '订单号',
	otc_details_lable_2: '卖家实名信息',
	otc_details_lable_3: '买家实名信息',
	otc_details_lable_4: '下单时间',
	otc_details_lable_5: '收款信息',
	otc_details_lable_6: '付款信息',
	otc_details_lable_7: '真实姓名',
	otc_details_lable_8: '银行卡号',
	otc_details_lable_9: '银行开户行',
	otc_details_lable_11: '支付宝姓名',
	otc_details_lable_12: '支付宝账号',
	otc_details_lable_13: '支付宝付款码',
	otc_details_lable_14: '微信姓名',
	otc_details_lable_15: '微信账号',
	otc_details_lable_16: '微信付款码',
	otc_details_tips_1: '交易提醒',
	otc_details_tips_2: '如果买家未向您转账付款，请务必在付款倒计时结束前点击“我要申诉”按钮，否则订单将自动确认，财产可能损失。',
	otc_details_tips_3: '交易已完成，法币已发放至您的账户',
	otc_details_btn_1: '我已付款',
	otc_details_btn_2: '确认收款',
	otc_details_btn_3: '确认接单',
	otc_details_btn_4: '取消',
	otc_details_btn_5: '取消申诉',
	otc_details_btn_6: '申诉',
	otc_details_phone_1: '即将向该号码呼出',
	otc_details_phone_2: '立即呼出',
	otc_details_select_label: '选择支付方式',
	otc_details_toast_1: '请等待卖家审核收款',
	otc_details_toast_2: '确定收款成功',
	otc_details_toast_3: '确认成功',
	otc_details_toast_4: '取消成功',
	otc_details_toast_5: '撤销成功成功',
	otc_payment_bank: '银联',
	otc_payment_alipay: '支付宝',
	otc_payment_wechat: '微信',
	otc_time_m: '分',
	otc_time_s: '秒',
	
	// OTC 发布广告
	otc_publish_ad:'发布广告',
	otc_publish_tab_1:'我要买',
	otc_publish_tab_2:'我要卖',
	otc_publish_text:'选择交易币种',
	otc_publish_text_1:'价格',
	otc_publish_text_2:'交易数量',
	otc_publish_text_3:'单笔最小成交额',
	otc_publish_text_4:'单笔最大成交额',
	otc_publish_text_5:'收款方式',
	otc_publish_text_6:'交易密码',
	otc_publish_pay_1:'银联',
	otc_publish_pay_2:'支付宝',
	otc_publish_pay_3:'微信',
	otc_publish_input_1:'请输入价格',
	otc_publish_input_2:'请输入数量',
	otc_publish_input_3:'请输入单笔最小成交额',
	otc_publish_input_4:'请输入单笔最大成交额',
	otc_publish_input_5:'未设置收款方式',
	otc_publish_input_6:'请输入交易密码',
	otc_publish_tips_1:'注意事项',
	otc_publish_tips_2:'请务必收到货款后，再确认收款',
	otc_publish_tips_3:'请核实款项来源及转账备注，以免银行卡被银行冻结',
	otc_publish_button:'立即发布',
	otc_publish_code:'验证码',
	otc_publish_reset:'重新获取',
	otc_publish_toast_1:'请输入最低限量',
	otc_publish_toast_2:'请输入最高限量',
	otc_publish_toast_3:'最高限量不能小于最低限量',
	otc_publish_toast_4:'最小限量不能大于需求数量',
	otc_publish_toast_5:'最大限量不能大于需求数量',
	otc_publish_toast_6:'发布成功',
	otc_publish_record:'发布记录',
	otc_publish_record_cancel:'撤销',
	otc_publish_record_price:'价格',
	otc_publish_record_quantity:'数量',
	otc_publish_record_sjcj:'实际成交',
	otc_publish_record_status:'状态',
	otc_publish_record_toast:'撤销成功',
	
	
	// 转账
	convert_title: '转账',
	convert_text: '选择币种',
	convert_text_1: '接收地址',
	convert_text_2: '数量',
	convert_text_3: '可用数量',
	convert_text_4: '交易密码',
	convert_text_5: '手续费',
	convert_text_6: '确定',
	convert_input_1: '输入对方的接收地址',
	convert_input_2: '请输入转出数量',
	convert_input_3: '全部',
	convert_input_4: '请输入您的交易密码',
	convert_toast_1: '接收地址不能为空',
	convert_toast_2: '转账数量不能为空',
	convert_toast_3: '交易密码不能为空',
	convert_toast_4: '可用数量不足',
	convert_toast_5: '转账成功',

	
	// 投票
	vote_title_1:'共享投票',
	vote_title_2:'实时投票',
	vote_item_1:'进行中',
	vote_item_2:'全部',
	vote_item_3:'已结束',
	vote_text_1:'暂无数据',
	vote_text_2:'当前: 第',
	vote_text_3:'期',
	vote_text_4:'每期收益',
	vote_text_5:'投票金额',
	vote_text_6:'已完成',
	vote_text_7:'投票总额',
	vote_text_8:'投票起止时间',
	vote_text_9:'参与投票',
	vote_text_10:'认购',
	vote_text_11:'价格',
	vote_text_12:'认购数量',
	vote_text_13:'限额',
	vote_text_14:'实际支付',
	vote_text_15:'交易密码',
	vote_text_16:'请输入您的交易密码',
	vote_status_1:'未开启',
	vote_status_2:'进行中',
	vote_status_3:'已结束',
	vote_toast_1:'请输入认购数量',
	vote_toast_2:'请输入交易密码',
	vote_toast_3:'交易密码不正确',
	vote_toast_4:'认购成功',
	vote_record:'投票记录',
	vote_record_list_1:'单价',
	vote_record_list_2:'投票金额',
	vote_record_list_3:'实际成交数量',
	vote_record_list_4:'认购时间',



	// APP信息提示
	app_w1: '更新提示',
	app_w2: '检测到新版本',
	app_w3: '你的版本是',
	app_w4: '您没有登录',
	app_w5: '请稍后重试',

	// 登录页
	login_username: '账号',
	login_username_placeholder: '请输入注册手机号/邮箱',
	login_password: '密码',
	login_password_placeholder: '请输入密码',
	login_forget: '忘记密码',
	login_login: '登录',
	login_register: '创建账号',
	login_toast_loggingIn: '登陆中',
	login_toast_loginSuccess: '登陆成功',
	login_drag_1: '拖动滑块验证',
	login_drag_2: '验证通过',
	login_drag_3: '验证失败',

	// 注册页
	register_phone: '手机注册',
	register_email: '邮箱注册',
	register_username: '账号',
	register_username_phone_placeholder: '请输入手机号',
	register_username_email_placeholder: '请输入邮箱',
	register_code: '验证码',
	register_code_placeholder: '请输入验证码',
	register_sendCode: '发送验证码',
	register_sending: '正在发送',
	register_sendSuccess: '发送成功',
	register_next: '下一步',
	register_loginPassword: '登录密码',
	register_loginPassword_placeholder: '请设置登录密码',
	register_tradePassword: '交易密码',
	register_tradePassword_placeholder: '请设置交易密码',
	register_inviteCode: '邀请码',
	register_inviteCode_placeholder: '请输入邀请码',
	register_register: '注册',
	register_registerSuccess: '注册成功',

	// 忘记密码页
	forget_forget: '忘记密码',
	forget_username: '账号',
	forget_username_placeholder: '请输入注册手机号/邮箱',
	forget_code: '验证码',
	forget_code_placeholder: '请输入验证码',
	forget_sendCode: '发送验证码',
	forget_sending: '正在发送',
	forget_sendSuccess: '发送成功',
	forget_next: '下一步',
	forget_resetPassword: '重设密码',
	forget_message: '密码重设后您的账户将使用新密码登录',
	forget_newPassword: '新密码',
	forget_newPassword_placeholder: '请输入您的新密码',
	forget_againPassword: '确认密码',
	forget_againPassword_placeholder: '请确认您的新密码',
	forget_modify: '修改',
	forget_modifySuccess: '修改成功',

	// 首页
	index_navigationBox_item_1: '投票上币',
	index_navigationBox_item_2: '邀请好友',
	index_navigationBox_item_3: '邀请激活',
	index_navigationBox_item_4: '收款',
	index_navigationBox_item_5: '转账',
	index_navigationBox_item_6: '公募',
	index_navigationBox_item_7: '合约',
	index_navigationBox_item_8: '其他应用',
	index_tabs_1: '涨幅榜',
	index_tabs_2: '跌幅榜',
	index_tabs_3: '成交榜',
	index_info: '资讯',
	index_menu_item_1: 'AFIL矿池',
	index_menu_item_2: '共享投票',
	index_menu_item_3: '实时投票',
	index_menu_item_4: '保险基金',
	index_chengjiu: '成就明日之星',
	

	// 币币交易
	exchange_title: '币币交易',
	exchange_tabs_1: '当前委托',
	exchange_tabs_2: '历史记录',
	exchange_tabs_3: '交易记录',
	exchange_menu_title: '币币列表',
	exchange_toast_1: '请先登录再进行交易',
	exchange_toast_2: '价格不能小于0',
	exchange_toast_3: '数量不能小于0',
	exchange_title_1: '法币交易',
	exchange_record:'记录',
	exchange_record_tab_1:'当前委托',
	exchange_record_tab_2:'历史记录',
	exchange_record_tab_3:'交易记录',
	exchange_record_text_1:'暂无记录',
	exchange_record_text_2:'价格',
	exchange_record_text_3:'数量',
	exchange_record_text_4:'实际成交',
	exchange_record_cancel:'撤单',
	exchange_record_toast:'撤单成功',
	

	// 合约交易
	contract_title_1: '合约交易',
	contract_title_2: '保险合约',
	contract_currency_unit: '永续',
	contract_header_btn_1: '开仓',
	contract_header_btn_2: '平仓',
	contract_header_btn_3: '持仓',
	contract_button_1: '买入开多',
	contract_button_2: '买入平空',
	contract_button_3: '卖出开空',
	contract_button_4: '卖出平多',
	contract_button_5: '一键平仓',
	contract_button_6: '止盈止损',
	contract_trade_unit: '手',
	contract_tabs_1: '当前持仓',
	contract_tabs_2: '计划委托',
	contract_tabs_3: '当前委托',
	contract_tabs_4: '历史委托',
	contract_tabs_5: '平仓记录',
	contract_label_1: '成交均价',
	contract_label_2: '收益',
	contract_label_3: '预估强平价',
	contract_label_4: '收益率',
	contract_label_5: '止盈价',
	contract_label_6: '止损价',
	contract_label_7: '持仓量',
	contract_label_8: '保证金',
	contract_label_9: '可平量',
	contract_label_10: '委托量',
	contract_label_11: '委托价',
	contract_label_12: '保证金',
	contract_label_13: '成交量',
	contract_label_14: '成交价',
	contract_label_15: '手续费',
	contract_label_16: '委托方式',
	contract_label_17: '数量',
	contract_label_18: '所需保证金',
	contract_label_19: '所需保险金',
	contract_label_20: '开仓均价',
	contract_label_21: '止盈',
	contract_label_22: '止损',
	contract_label_23: '预计收益',
	contract_label_24: '开仓价格',
	contract_label_25: '平仓价格',
	contract_label_26: '收益',
	contract_label_27: '平仓手续费',
	contract_label_28: '平仓数量',
	contract_label_27: '收益率',
	contract_more_1: '合约设置',
	contract_more_2: '计算器',
	contract_prompt_1: '温馨提示',
	contract_prompt_2: '购买本项合约需要支付保险金，用于保障交易风险。',
	contract_menu_title: 'USDT合约',
	contract_toast_1: '请输入价格',
	contract_toast_2: '请输入数量',
	contract_toast_3: '平单成功',
	contract_toast_4: '价格不能小于0',
	contract_toast_5: '数量不能小于0',
	contract_toast_6: '请先登录再进行交易',
	contract_set_title: '合约设置',
	contract_set_label_1: '限价委托下单确认',
	contract_set_label_2: '市价委托下单确认',
	contract_calculator_title: '合约计算器',
	contract_calculator_tabs_1: '开多',
	contract_calculator_tabs_2: '开空',
	contract_calculator_label_1: '杠杆倍数',
	contract_calculator_label_2: '开仓价格',
	contract_calculator_label_3: '平仓价格',
	contract_calculator_label_4: '开仓数量',
	contract_calculator_toast_1: '请输入杠杆倍数',
	contract_calculator_toast_2: '请输入开仓价格',
	contract_calculator_toast_3: '请输入平仓价格',
	contract_calculator_toast_4: '请输入开仓数量',
	contract_calculator_btn: '计算',

	// 充币
	rechange_title: '充币',
	rechange_save_button: '保存二维码至相册',
	rechange_tips_title: '温馨提示',
	rechange_tips_info_1: '钱包地址禁止充值除',
	rechange_tips_info_2: '之外的其他资产，任何非',
	rechange_tips_info_3: '资产充值将不可找回。',
	rechange_tips_info_4: '充值地址不会经常发生变化，充值前请确认地址。',
	rechange_record: '充值记录',
	rechange_details: '充值详情',
	rechange_default_coinType: '普通充币',

	// 提币
	withdrawal_title: '提币',
	withdrawal_text_1: '输入或长按粘贴地址',
	withdrawal_text_2: '提币数量',
	withdrawal_text_3: '最小提币数量：',
	withdrawal_text_4: '全部',
	withdrawal_text_5: '可用数量：',
	withdrawal_text_6: '手续费',
	withdrawal_text_7: '实际到账',
	withdrawal_text_8: '验证码',
	withdrawal_text_9: '向手机号',
	withdrawal_text_10: '发送验证码',
	withdrawal_text_11: '请输入验证码',
	withdrawal_text_12: '获取验证码',
	withdrawal_text_13: '交易密码',
	withdrawal_text_14: '请输入交易密码',
	withdrawal_tips_title: '温馨提示',
	withdrawal_tips_1: '最小提币数量为：',
	withdrawal_tips_2: '为了保证资金安全，当您账户安全策略变更、密码修改、我们会对人工审核，请耐心等待。',
	withdrawal_tips_3: '请务必确认电脑及浏览器安全，防止信息被篡改或泄露。',
	withdrawal_record: '提币记录',
	withdrawal_details: '提币详情',
	withdrawal_details_text_1: '提交成功',
	withdrawal_details_text_2: '提现已提交，请等待审核',
	withdrawal_toast_1: '请输入提币地址',
	withdrawal_toast_2: '请输入提币数量',
	withdrawal_toast_3: '请输入验证码',
	withdrawal_toast_4: '请输入交易密码',
	withdrawal_toast_5: '提币申请成功',
	withdrawal_basic: '普通提币',
	withdrawal_your: '您的',
	withdrawal_quest: '提现已发起',
	withdrawal_look: '查看',

	// 划转
	asset_transfer_toast_1: '请输入划转数量',
	asset_transfer_toast_2: '当前可用数量不足',
	asset_transfer_toast_3: '划转成功',
	asset_transfer_record_info_1: '转出账户',
	asset_transfer_record_info_2: '转入账户',
	asset_transfer_type_1: '币币账户',
	asset_transfer_type_2: '合约账户',
	asset_transfer_type_3: '法币账户',
	asset_transfer_type_4: '保证金账户',
	asset_transfer_select_title: '选择账户',


	// 我的团队
	myTeam_title: '我的团队',
	myTeam_card_title_1: '今日返佣',
	myTeam_card_title_2: '累计返佣',
	myTeam_card_title_3: '分享人数',
	myTeam_card_title_4: '团队人数',
	myTeam_invitationRecord: '邀请记录',
	myTeam_invitationFriend: '邀请好友',
	myTeam_saveImg: '保存图片至相册',
	myTeam_choosePoster: '选择海报',
	myTeam_record_title: '权益证明',

	// 帮助中心
	help_title: '操作教程',
	help_desc: '我将竭尽所能为您排忧解难哦',
	help_detail_title: '帮助详情',


	// 分享图片
	share_img_1: '../../static/share/img-share-01.jpg',
	share_img_2: '../../static/share/img-share-02.jpg',
	share_label_1: '邀请码：',
	share_label_2: '邀请您加入',

	//设置
	set_title: '设置',
	set_gerzl: '个人资料',
	set_shoukfs: '收款方式',
	set_lang: '语种选择',
	set_logout: '退出登录',

	// 个人中心
	set_userInfo: '个人资料',
	set_avatar: '头像',
	set_nickName: '昵称',
	set_xiugnc: '修改昵称',
	set_newnc: '新的昵称',
	set_qsrnxdnc: '请输入您新的昵称',
	set_shoujh: '手机号',
	set_chujrz: '初级认证',
	set_gaojrz: '高级认证',
	set_weirz: '未认证',
	set_renzz: '认证中',
	set_yirz: '已认证',
	set_renzsb: '认证失败',
	set_jiaoyyz: '交易验证',
	set_never: '永不输入交易密码',
	set_caozcg: '操作成功',
	set_shousmm: '手势密码',
	set_xiugsjh: '修改手机号',
	set_xiugma: '修改密码',
	set_xiugnc: '修改昵称',



	// 提示语
	toast_input_phone: '请输入手机号/邮箱',
	toast_input_email: '请输入邮箱',
	toast_input_usernameAll: '请输入注册的手机号/邮箱',
	toast_input_verificationCode: '请输入验证码',
	toast_input_password: '请输入登录密码',
	toast_input_dblpassword: '请再次输入登录密码',
	toast_input_transactionPassword: '请输入交易密码',
	toast_input_invitationCode: '请输入邀请码',
	toast_input_realName: '请输入您的真实姓名',
	toast_input_idCard: '请输入您的身份证号码',
	toast_input_alipay: '请输入支付宝收款账号',
	toast_input_wechat: '请输入微信收款账号',
	toast_input_payee: '请输入您的收款人',
	toast_input_bankCard: '请输入您的银行卡号',
	toast_input_bankAddress: '请输入您的银行地址',
	toast_username_false: '用户名不正确',
	toast_null_password: '密码不能为空',
	toast_null_name: '姓名不能为空',
	toast_null_idCard: '身份证号码不能为空',
	toast_please_login: '请先登录',
	toast_please_more_100_price: '请输入倍数为100的金额',
	toast_please_more_100_quantity: '请输入倍数为100的数量',
	toast_please_payCode: '请上传您的收款码',
	toast_please_carrier: '请先申请成为承运商',
	toast_success_buyNow: '抢购成功',
	toast_success_exchange: '抢购成功',
	toast_success_refresh: '刷新成功',
	toast_noOpen: '暂未开放',
	toast_notsmyz: '您还没有实名认证，快去实名认证吧!',
	toast_password_false: '密码不正确',
	toast_login_doing: '登录中',
	toast_success_send: '发送成功',
	toast_dqmmbnwk: '当前密码不能为空',
	toast_dqmmgsbzq: '当前密码格式不正确',
	toast_xmmbnwk: '新密码不能为空',
	toast_xmmgsbzq: '新密码格式不正确',
	toast_lcmmbyz: '两次密码不一致',
	toast_dlmmxgcg: '登录密码修改成功',
	toast_jymmxgcg: '交易密码修改成功',
	toast_qsrwt: '请输入您的问题',
	toast_qsrssyy: '请输入您申诉的原因',
	toast_bcz: '保存中',
	toast_bccg: '保存成功',
	toast_qsrmm: '请输入密码',
	toast_liccg: '理财成功',
	toast_qxzsl: '请选择数量',
	toast_quedtj: '确定提交',
	toast_qsrzs: '请输入整数',
	toast_input_address: '请输入或粘入地址',
	toast_input_otherAddress: '地址别名',
	toast_please_quantity: '请输入数量',
	toast_chedcg: '撤单成功',
	toast_copySuccess: '复制成功',
	toast_noLogin: '您没有登陆',
	toast_verified: '已认证',

	toast_unsearch_wallet_name: '未搜索到的钱包名称',
	
	share_desc:'专业安全的金融资产交易平台',
	account_create_confirm:'确定创建',
	account_create_success:'创建成功',
	account_import_key_addr:'请填写您的私钥地址',
	account_import_open:'开始导入',
	account_import_succ:'导入成功',
	g_asset:'资产',
	g_trade:'交易',
	asset_toast_jscg:'接收成功',

	gateway_text_1:'添加网关',
	gateway_text_2:'请选择需要添加的网关',
	gateway_text_3:'风险提示',
	gateway_text_4:'NT风险提示',
	gateway_text_5:'1.NT提供的是去中心化的底层平台',
	gateway_text_6:'2.NT既不拥有账户里的各种虚拟货币，也不拥有网关的信任额度',
	gateway_text_7:'3.所以用户对网关的信任必须建立在对网关的重复了解和信任的基础上',
	gateway_text_8:'4.NT不对网关的信用做担保，请用户对网关谨慎选择',
	gateway_text_9:'已知信任NT风险',
	
	video_content_text_1:'去中心化金融生态 分布式存储技术',
	video_content_text_2:'去中心化链上交易',
	video_content_text_3:'创建地址',
	video_content_text_4:'导入地址',
	
	index_text_1:'今日收益',
	index_text_2:'最佳持币',
	index_text_3:'最低持币',
	index_text_4:'转账',
	index_text_5:'矿池',
	index_text_6:'账本',
	index_text_7:'收款',
	index_text_8:'IPFS',
	index_text_9:'DEFI生态',
	index_text_10:'发行',
	index_text_11:'社区',
	index_text_12:'行情',
	index_text_13:'更多',
	index_text_14:'交易对',
	index_text_15:'最新价',
	index_text_16:'涨跌幅',
	
	index_toast_1:'已认证',
	index_toast_2:'请先完成实名认证',
	
	mine_text_1:'发布交易',
	mine_text_2:'激活矿工',
	mine_text_3:'分享APP',
	mine_text_4:'账户管理',
	mine_text_5:'语言切换',
	mine_text_6:'在线客服',
	mine_text_7:'操作教程',
	mine_text_8:'安全中心',
	mine_text_9:'官网地址',
	mine_text_10:'区块浏览器',
	mine_text_11:'敬请期待',
	mine_text_12:'开源地址',
	mine_text_13:'版本号',
	
	mine_status_1:'未激活',
	mine_status_2:'激活中',
	mine_status_3:'已激活',

	}
export default messagesCn
