const messagesCn = {
	g_website: 'NT',
	g_login: 'Login',
	g_register: 'Register',
	g_more: 'More',
	g_more_t: 'More>>',
	g_password: 'Password',
	g_sendCode: 'Send verification code',
	g_sending: 'Sending',
	g_sendSuccess: 'Send successful',
	g_enter: 'OK',
	g_confirm: 'Confirm',
	g_cancel: 'Cancel',
	g_default: 'default',
	g_buy: 'Buy',
	g_buyIn: 'Buy',
	g_sell: 'sell',
	g_sellOut: 'Sell',
	g_time: 'Time',
	g_status: 'Status',
	g_price: 'Price',
	g_quantity: 'Quantity',
	g_limited: 'Limited',
	g_valuation: 'valuation',
	g_position: 'Direction',
	g_decimal: 'bit',
	g_record: 'Record',
	g_loading: 'Loading',
	g_consume: 'Consume',
	g_mark: 'Remarks',
	g_quota: 'quota',
	g_buyNow: 'Buy Now',
	g_period: 'period number',
	g_search: 'Search',
	g_rechange: 'Recharge',
	g_withdrawal: 'Withdrawal',
	g_exchange: 'Exchange',
	g_coinType: 'Currency',
	g_canUse: 'Available',
	g_freeze: 'Freeze',
	g_amount: 'Converted',
	g_total: 'Total',
	g_tradeAmount: 'Transaction Amount',
	g_waitRelease: 'To be released',
	g_burnFreeze: 'Burn Freeze',
	g_doneRelease: 'Released',
	g_dividend: 'dividend',
	g_resubmit: 'Resubmit',
	g_phone: 'Mobile phone number',
	g_name: 'Name',
	g_idCard: 'ID Card',
	g_nextStep: 'Next',
	g_copy: 'copy',
	g_share: 'Share',
	g_invite: 'Invite',
	g_coinLength: 'Number of coins',
	g_no: 'No',
	g_yes: 'Yes',
	g_username: 'Account name',
	g_showPayType: 'Show the payment method',
	g_save: 'Save',
	g_setting: 'Settings',
	g_chooseCoinType: 'Select currency',
	g_linkType: 'Link Type',
	g_rechangeAddress: 'Recharge address',
	g_withdrawalAddress: 'Withdrawal address',
	g_copy: 'copy',
	g_send: 'Send',
	g_hello: 'Hello',
	g_code: 'Verification code',
	g_user: 'Account',
	g_prompt: 'Prompt',
	g_rechange_quantity: 'Recharge quantity',
	g_rechange_address: 'Recharge address',
	g_rechange_status: 'Recharge status',
	g_transfer: 'transfer',
	g_deposit: 'Deposit',
	g_deposit_record: 'Deposit Record',
	g_level: 'level',
	g_performance: 'Performance',
	g_mutual_transfer: 'Exchange',
	g_apply: 'Apply',
	g_coming_soon: 'Data connection, please look forward to it',
	g_recipient: 'Recipient',
	g_sender: 'Sender',
	g_obtain: 'Harvest',
	g_type: 'Type',
	g_all: 'All',
	g_available_balance: 'Available balance',
	g_add: 'Add',
	g_noopen: 'not open',
	g_atLast: 'At the end',
	g_fees: 'Handling fee',
	g_coinAddress: 'Blockchain transaction',
	g_sumbitSuccess: 'Submission successful',
	g_modify: 'Modify',
	g_modifying: 'Modifying',
	g_modifySuccess: 'Modification successful',
	g_enterBind: 'Confirm binding',
	g_binding: 'Binding',
	g_bindSuccess: 'Binding successful',
	g_close: 'Close',
	g_actual: 'Actual deal',
	g_limitOrder: 'Limit Order',
	g_limit: 'Limit price',
	g_marketOrder: 'Market Order',
	g_market: 'market price',
	g_digits_4: '4',
	g_digits_3: '3',
	g_digits_2: '2',
	g_revoke: 'Cancel order',
	g_guarantee: 'Margin',
	g_noData: 'No data temporarily',
	g_orders: 'Order',
	g_tradeRate: 'Transaction Rate',
	g_buyQuantity: 'Buy Quantity',
	g_sellQuantity: 'Sell Quantity',
	g_totalMoney: 'Total Money',
	g_service_privacy: 'Service Agreement',
	g_policy_privacy: 'Privacy Policy',
	g_project_introdution: 'Project Introduction',
	g_version_diary: 'Version log',
	g_current_p: 'Current version:',
	g_about_we: 'About us',
	g_account_manage: 'Account Management',
	g_tradepassword: 'Trade password',
	g_loginpassword: 'Login password',
	g_is_bottom: 'To the end',
	g_people: 'people',
	g_submit: 'Submit',
	g_download: 'Download',
	g_time_h:'H',
	g_time_m:'M',
	g_time_s:'S',
	

	// 关于
	about_info: 'HBA uses blockchain technology to build various applications including anonymous network communication, computing power sharing, storage space sharing, bandwidth sharing, reputation sharing (credit guarantee), etc., and cooperates with various service providers and application providers to build Public chain, alliance chain and private chain application system, thus applying HBA to various practical application scenarios. ',
	about_policy: 'Privacy Policy',
	about_policy_1: '1 General: HBA and its affiliates (hereinafter referred to as "HBA", "we") are committed to protecting and respecting your privacy. ',
	about_policy_2: 'This privacy policy governs our collection, processing and use of your personal information. We define "personal information" as personally identifiable information, such as your name, address, email address, transaction, etc. ',
	about_policy_3: 'The purpose of this privacy policy is to inform you:',
	about_policy_4: '1.1 The personal information we may collect about you and how to use it;',
	about_policy_5: '1.2 We use information about IP addresses and our use of cookies;',
	about_policy_6: '1.3 Disclosure of personal information to third parties;',
	about_policy_7: '1.4 Your ability to correct, update and delete your personal information; and the security measures we have formulated can prevent the loss, abuse or tampering of personal information under our control;',
	about_policy_8: '2 Collection and use of personal information: If you use this website, open an account to use the platform or perform any transactions on the platform, we may collect your personal information. The types of personal information we collect may include:',
	about_policy_9: '2.1 your name',
	about_policy_10: '2.2 Your address. ',
	about_policy_11: '2.3 Your phone number. ',
	about_policy_12: '2.4 Your email address. ',
	about_policy_13: '2.5 Your account information. ',
	about_policy_14: '2.6 Your transaction',
	about_policy_15: 'We may use your personal information for the following purposes:',
	about_policy_16: '2.a allows you to open and operate accounts on the platform. ',
	about_policy_17: '2.b enables you to complete transactions on the platform. ',
	about_policy_18: '2.c If you contact us, we will respond to your questions. ',
	about_policy_19: '2.d Analyze the usage of our website. ',
	about_policy_20: '2.e According to the requirements of regulatory purposes',
	about_policy_21: '2.f Provide you with information about products and promotions that may be of interest to you and third parties, but only if you have explicitly agreed to receive such information. ',
	about_policy_22: '2.g Conduct market research, such as surveying users’ needs and opinions on our performance. ',
	about_policy_23: '3 Security functions and strategies for the transmission of payment card details: HBA is fully compliant with PCI DSS LEVEL 2. You can view the information here. In addition, all sensitive user data is protected by multiple layers of encryption and security to prevent unauthorized access. ',
	about_policy_24: '4 IP address: We may collect information about your computer (including available IP address, operating system and browser type) for system management and report aggregate information to our advertisers. This is statistical data about the browsing behavior and patterns of our users, and does not identify any individual. ',
	about_policy_25: '5 Cookies: We use the information collected from cookies to evaluate the effectiveness of our website, analyze trends and manage the platform. The information collected from cookies allows us to determine which parts of our website are most visited and the difficulties that visitors encounter when visiting our website. ',
	about_policy_26: 'With this knowledge, we can improve the quality of your experience on the platform by identifying and providing more of the most wanted features and information, as well as solving access difficulties. We also use cookies and/or technology called web errors or clear gifs, which are usually stored in emails to help us confirm your receipt. We use third-party service providers to help us better understand the use of our website Happening. Our service provider will place cookies on your computer\'s hard drive and will receive information we choose.This information will introduce us to the way visitors browse our website,the products viewed,and general transaction information.Our service providers analyze this information and provide us with aggregate reports.The information and analysis provided by our service providers will be used to help us better understand the interests of visitors on our website and how to better serve these interests.The information collected by our service providers may be associated with and combined with the information we collect about you when using the platform.By using our website,you agree that we can use cookies to achieve the above - mentioned purposes.',
	about_policy_27: '6 Disclosure of personal information: We use personal information for the purposes indicated when you provide us with such information, and/or for the purposes specified in this privacy policy and/or for purposes otherwise permitted by law. ',
	about_policy_28: 'For these limited purposes, we may provide the personal information you provide to us to our affiliates, agents, representatives, trusted service providers and contractors. ',
	about_policy_29: 'In the case of mergers, divestitures or other company reorganizations, we may also share users\'personal information with financial institutions,insurance companies or other companies.',
	about_policy_30: 'According to legal requirements, we may also share users\'personal information with law enforcement agencies or regulatory agencies.Unless otherwise required or permitted by law,any third party receiving or accessing personal information must require us to protect such personal information and only use it to perform services for you or the HBA.',
	about_policy_31: 'We will ensure that any such third parties are aware of our obligations under this privacy policy, and we will enter into contracts with third parties, and these third parties are bound by their terms no less than the protection of any personal information disclosed to them Obligations that you impose on us in accordance with this privacy policy or in accordance with applicable data protection laws. ',
	about_policy_32: '7 Correction, update, and deletion of personal information: You have the right to access your personal information and send us an email to: vcakefu@yeah.net, requesting correction, updating and blocking inaccurate data. You can also send us an email request to delete or destroy your account, and HBA will only take action if it does not violate legal and regulatory obligations. According to your written request, we will notify you of the personal information we hold about you and the use and general disclosure of your personal information. We will also give you a copy of the personal information we retain, and access to your personal information may be charged the lowest fee. ',
	about_policy_33: '8 Security: We have implemented security measures to ensure the confidentiality of your personal information and protect your personal information from loss, misuse, tampering or destruction. Only persons authorized by HBA can access your personal information, and these persons must treat this information as confidential information. The current security measures will be reviewed from time to time in accordance with the technological development of the law. ',
	about_policy_34: '9 Retention of personal information: Taking into account the purposes described in this privacy policy and our own legal and regulatory requirements, we will retain your personal information as long as we need to do so. In accordance with our record keeping obligations, we will retain account and personal information for at least five years after the user is closed. ',
	about_policy_35: '10 Links: This website may have links to other websites and resources provided by third parties. This privacy policy only applies to our website. Visiting these third-party websites or sources requires you to leave our website. We do not control these third-party websites or any content contained therein. You agree that we are not responsible for any third-party websites (including but not limited to their content, policies, failures, promotions, products), services or actions caused by these websites Any damage, loss, failure, etc. We encourage all the policies, rules, terms and regulations of each website you visit, including the privacy policy. ',
	about_policy_36: '11 Marketing: You have the right to ask us not to process your personal information for marketing purposes. You can exercise your rights by checking certain boxes on the form that we use to collect your personal information to prevent such processing. ',
	about_policy_37: '12 Changes: Our website policies, content, information, promotions, disclosures, disclaimers and functions can be modified, updated or supplemented at any time without prior notice, and are determined by HBA alone. If we change this privacy policy, we will take steps to post the revised privacy policy on our website. ',
	about_policy_38: 'If you have any questions about our privacy policy, please contact us at the following email address: vcakefu@yeah.net',

	about_agreement: 'User Agreement',
	about_agreement_1: 'This agreement starts on September 30, 2020',
	about_agreement_2: 'The final resolution right belongs to the FIEX operator platform',
	about_agreement_3: 'Welcome to read the FILEX platform registration agreement (hereinafter referred to as "this agreement"). ',
	about_agreement_4: 'Special reminder: Before you become a platform user, you must read, agree and accept all the terms and conditions contained in this agreement, including the following documents, terms and conditions that are expressly stated and incorporated due to being mentioned. ',
	about_agreement_5: 'Your application for registration as a platform user indicates that you have fully read, understood and accepted all the terms and conditions contained in this agreement without any additional conditions, including the terms and contents of this agreement and other documents cited Legal meaning. ',
	about_agreement_6: 'You only need to check "I have read and agree to the filex platform user registration agreement" on the registration page and successfully register as a user in accordance with the registration procedures stipulated on this website. Your behavior means that you agree and sign this service agreement. This service agreement does not involve legal relations and legal disputes between you and other users of this website due to online transactions. ',
	about_agreement_7: 'Important note: We hereby remind you:',
	about_agreement_8: '1. The digital asset itself is not issued by any financial institution or company or this website;',
	about_agreement_9: '2. The digital asset market is new, unconfirmed, and may not grow;',
	about_agreement_10: '3. Digital assets are mainly used by speculators in large numbers, and the retail and commercial markets are relatively less used. Digital asset transactions are extremely risky. They are traded all day long, without fluctuation restrictions, and prices are easily affected by market makers and global governments. Fluctuates greatly under the influence of policy;',
	about_agreement_11: '4. Due to the formulation or modification of laws, regulations and regulatory documents of various countries, digital asset transactions may be suspended or prohibited at any time. ',
	about_agreement_12: 'Digital asset trading has extremely high risks and is not suitable for most people. You understand and understand that this investment may result in partial or total loss, so you should decide the amount of investment based on the degree of loss you can bear. You understand and understand that digital assets will generate derivative risks, so if you have any questions, it is recommended to seek the assistance of a financial advisor first. In addition, in addition to the risks mentioned above, there will also be unpredictable risks. You should carefully consider and use clear judgment to evaluate your financial situation and the above-mentioned risks before making any decision to buy or sell digital assets, and bear all the losses arising therefrom. We are not responsible for this. ',
	about_agreement_13: 'One, user qualification',
	about_agreement_14: '1.1 You should have full capacity for civil rights and capacity for civil conduct, and be able to independently bear civil liability. ',
	about_agreement_15: '1.2 does not belong to the following groups of people that the platform provides user services:',
	about_agreement_16: '(1) Natural persons under the age of 18 and over 70;',
	about_agreement_17: '(2) Investors who have no investment experience in non-principal-guaranteed financial products or who are not familiar with the Internet. ',
	about_agreement_18: 'Two, user account management',
	about_agreement_19: '2.1 Your registered account on the platform is for personal use only, not for lending or transfer. Please keep your account information such as username and password in a safe place. You will be responsible for any loss caused by its disclosure or embezzlement. ',
	about_agreement_20: '2.2 All actions implemented by logging in with your registered account are regarded as your own actions, and the legal consequences arising therefrom shall be borne by you. If you find that your account has been stolen or used illegally, you should immediately notify the platform to freeze funds in an effective manner to protect the safety of your property; at the same time, please understand that the platform requires a reasonable period of time to take action in the above situation. Before that, the platform No responsibility for any loss caused by any illegal use. ',
	about_agreement_21: '2.3 In the event of one of the following circumstances, the platform has the right to unilaterally suspend, interrupt or terminate the provision of related services to you based on independent judgment without notice, and shall not be liable for the losses arising therefrom:',
	about_agreement_22: '(1) The platform believes that the personal information you provide does not have authenticity, validity or integrity, including but not limited to the misappropriation of other\'s certificate information for registration,mismatch of authentication information,etc.;',
	about_agreement_23: '(2) When the platform believes that there are abnormal transactions or transactions may be suspected of money laundering, cash out, pyramid schemes, terrorist activities and other illegal activities;',
	about_agreement_24: '(3) The platform finds that you have used illegal or improper technical means to compromise transaction security or affect fair transactions, including but not limited to tampering with transaction data, stealing customer information, stealing transaction data, attacking other users through the platform, etc. ;',
	about_agreement_25: '(4) When the platform believes that your account has been stolen, fraudulently used or other risks;',
	about_agreement_26: '(5) The platform believes that you have violated the various rules and spirits stipulated in this agreement;',
	about_agreement_27: '(6) Other situations where the platform needs to take measures to ensure transaction safety and fairness. ',
	about_agreement_28: '2.4 You agree and authorize that when the platform requires system upgrades and transformations, product functional modules splitting or merging, changes in operating entities, and any other necessary adjustments due to strategic adjustments, data related to you (including but not limited to User registration information, user personal information, transaction data and other related information) are synchronized to the adjusted portal website, APP, client or other related applications. When you use such applications, you can log in and operate with your original account. ',
	about_agreement_30: 'You confirm and authorize here: The application or instruction submitted to the platform during your transaction through the platform will be issued by the platform to the depository bank. ',
	about_agreement_31: 'Three, services and fees',
	about_agreement_32: '3.1 Service',
	about_agreement_33: '3.1.1 FILEX trading platform, as a financial technology service platform, provides users with comprehensive financial information services. ',
	about_agreement_34: '3.1.2 Please make your own judgment and confirm the risks of related projects on the platform. The platform does not assume any responsibility for the transactions between you and the parties involved. ',
	about_agreement_35: '3.1.3 Third-Party Liability In any case, the third party shall be responsible for the service provided by a third party such as a bank during your use of the platform\'s services,and the platform shall not be liable.Circumstances where the platform is not liable include but are not limited to: ',
	about_agreement_36: '(1) Loss or liability caused by the third party\'s failure to operate in accordance with your or platform instructions;',
	about_agreement_37: '(2) The funds are not received in time due to third party reasons and related losses or liabilities;',
	about_agreement_38: '(3) Loss or liability caused by a third party’s restriction on transaction limits or times. ',
	about_agreement_39: '3.2 Fees',
	about_agreement_40: '3.2.1 The platform temporarily does not charge users for using the platform. ',
	about_agreement_41: '3.2.2 Despite the provisions of the preceding paragraph, the platform reserves the right to issue notices to adjust the charging standards and in accordance with the operating strategy within the scope of the law.about_agreement_42: \'The right to charge. After the notice is released, if you continue to use the platform services, it is deemed that you have approved and accepted the content of the notice. ',
	about_agreement_43: '3.3 Other',
	about_agreement_44: '3.3.1 Other expenses in the process of using the services provided by the platform (including but not limited to network usage fees, communication fees, data delivery fees, etc.) shall be borne by you. ',
	about_agreement_45: '3.3.2 You should bear the corresponding taxes and fees in accordance with applicable laws and regulations on the income you obtain from transactions completed using the services provided by the platform. ',
	about_agreement_46: 'Four. Your information',
	about_agreement_47: '4.1 Your information includes: any information you provide to the platform or other users during the registration or login process, in any public information area (including the message box or feedback area), or through any email or mobile phone text message. You are fully responsible for your information, and the platform only serves as a channel for you to distribute and publish your information online. ',
	about_agreement_48: '4.2 You should provide true, valid and complete information according to the requirements of the platform. The information shall not: be fraudulent, false, inaccurate or misleading; infringe any third party\'s copyright,patent rights,trademark rights,trade secrets or other proprietary rights or publication rights or privacy rights;violate any applicable laws or regulations;Contains content that insults or slanders others,infringes upon the legal rights and interests of others;Contains content that is obscene,pornographic,gambling,violence,murder,terrorism,or abetting crime;Contains content that may damage,change,delete,adversely affect,secretly intercept,and unauthorized access Or requisition any viruses,Trojan horses,worms,time bombs,delete flies,Easter eggs,spyware or other computer programs from any system,data or personal information;direct or indirect links to links or listings that you have no right to link or list Any URL or content.',
	about_agreement_49: '4.3 In order to enable the platform to use the information you submit to the platform, so that the platform does not violate any rights you may have in the information, you should agree to grant the platform a non-exclusive, global, permanent, irrevocable, The right to be free of royalty-free and separable licensing (through multi-level licensing) to exercise your rights in your data (in any known or currently unknown media) related to your data. The platform will use your information in accordance with the privacy policy. ',
	about_agreement_50: '4.4 You are obliged to maintain and update your information to ensure that it is true, valid and complete. If you provide any wrong, false, outdated or incomplete information, or the platform suspects that the information is wrong, false, outdated or incomplete based on its independent judgment, the platform has the right to refuse your use of part or all of the platform’s services or take other processing Measures. In this case, the platform does not bear any responsibility, and you agree to bear any direct or indirect expenses or losses arising therefrom. ',
	about_agreement_51: '4.5 If you fail to update the basic information in a timely manner, the platform services cannot be provided or any error occurs in the provision, you shall not use this as a reason for canceling the transaction, and the platform shall not bear any responsibility, and all consequences shall be borne by you. ',
	about_agreement_52: '4.6 In addition to this agreement, you shall also abide by all the rules published and updated by the platform from time to time, including but not limited to announcements, product process descriptions, platform project descriptions, risk warnings, etc. ',
	about_agreement_53: '4.7 You agree that the platform shall disclose your relevant information on the platform or other channels in accordance with the requirements of laws, regulations and industry supervision. ',
	about_agreement_54: 'Five. Entry and interference',
	about_agreement_55: '5.1 Without the express or written permission of the platform, you may not use any robot, spider software, refreshing software or other automatic methods to enter the website for any purpose. ',
	about_agreement_56: '5.2 In addition, you agree that you will not:',
	about_agreement_57: '(1) Conduct any behavior that causes or may cause (as determined by the platform at its discretion) unreasonable or disproportionate heavy load on the internal structure of the platform;',
	about_agreement_58: '(2) Make copies, copy, modify, make derivative works, distribute or publicly display any content of the website (except your information) without the prior express written permission of the platform and appropriate third parties (if applicable) ;',
	about_agreement_59: '(3) Interfering with or attempting to interfere with the normal work of the website or any activities on the website;',
	about_agreement_60: '(4) Robots that cross the platform may be used to prevent or restrict access to the website to exclude probes or other forms. ',
	about_agreement_70: 'Six, fraud',
	about_agreement_71: 'You must not engage in fraud in the process of using platform services. If the platform has reasonable grounds to suspect that you have participated in fraudulent activities related to the platform, the platform may unilaterally decide to take measures such as suspending or terminating your account at its discretion, and will not bear any responsibility for the losses caused to you. ',
	about_agreement_72: 'Seven, breach of contract',
	about_agreement_73: 'Without limiting other relief, the platform may restrict your activities, issue warnings about your behavior, temporarily suspend, suspend or terminate your user qualifications indefinitely, and refuse to provide you if the following circumstances occur service:',
	about_agreement_74: '7.1 You violated this agreement or included documents in this agreement;',
	about_agreement_75: '7.2 The platform cannot verify the information or information you provide to the platform;',
	about_agreement_76: '7.3 Your actions may cause losses or legal liabilities to other users of the platform, platform partners or the platform. ',
	about_agreement_77: 'eight, information collection, use, sharing authorization and protection terms',
	about_agreement_78: '8.1 Collect your information',
	about_agreement_79: '8.1.1 In order to better provide you with platform services, you agree and authorize the company to obtain your information through the following channels:',
	about_agreement_80: '8.1.1.1 Collect the information you keep in the company\'s affiliates;',
	about_agreement_81: '8.1.1.2 Collect the information you keep with our company\'s partners(including but not limited to securities institutions, insurance institutions, banks, fund companies,payment institutions, cooperative branches, etc., the same below);',
	about_agreement_82: '8.1.1.3 Inquire, print, and retain your information from administrative agencies, judicial agencies, associations, third-party industry media and other institutions;',
	about_agreement_83: '8.1.1.4 Collect your information from natural persons, legal persons or other organizations that legally retain your information. ',
	about_agreement_84: '8.1.2 You agree and authorize the company to collect your information including but not limited to:',
	about_agreement_85: '8.1.2.1 Your identity information, including but not limited to name/name, document number, document type, address, telephone number, platform account or partner account authentication information and other identity information;',
	about_agreement_86: '8.1.2.2 Any data and information provided and formed when you apply for and use platform services;',
	about_agreement_87: '8.1.2.3 Any data and information that you keep and form with the company’s affiliates and partners, including but not limited to your platform account and/or securities account, bank account, fund account information, you and the company Any agreements existing between affiliated companies or partners and your performance under these agreements, your behavioral data on the company\'s affiliates or partner platforms,etc.;',
	about_agreement_88: '8.1.2.4 Your credit information, including but not limited to your credit records and credit reports;',
	about_agreement_89: '8.1.2.5 Your property information, including but not limited to your store/business operating status, fiscal and tax information, real estate information, vehicle information, investment and financial information such as funds, insurance, stocks, trusts, creditor\'s rights,and liability information;',
	about_agreement_90: '8.1.2.6 Any information you keep in administrative agencies and judicial agencies, including but not limited to household registration information/business information, litigation information, enforcement information, illegal and criminal information, etc.;',
	about_agreement_91: '8.1.2.7 Relevant information about other natural persons, legal persons or other organizations that you keep in relation to your application or use of platform services. ',
	about_agreement_92: '8.1.3 You agree that the company can use data collection devices such as "Cookies" on the platform and certain related web pages, collect your information by manual or automatic tracking methods, and can treat you through manual or automatic procedures Analysis and evaluation of the data. ',
	about_agreement_93: '8.2 Use of your information You agree and authorize the company to use your information for the following purposes:',
	about_agreement_94: '8.2.1 Use the entire user database (including your information) to create a data analysis model;',
	about_agreement_95: '8.2.2 Compare and verify the accuracy of information and cross-validate with a third party;',
	about_agreement_96: '8.2.3 In order to let you know or understand the platform\'s services,send it to you via email,platform site letter,information sending channel of our company\'s affiliates or partners, mobile phone text messages, fax, WeChat, QQ or other methods Notification of product updates, service status, etc., marketing activities and other commercial electronic information;',
	about_agreement_97: '8.2.4 The company, its affiliates or partners need to prevent or prevent illegal activities for risk prevention and control;',
	about_agreement_98: '8.2.5 Other purposes with your permission or related to the provision of services to you. ',
	about_agreement_99: '8.3 Share your information',
	about_agreement_100: 'The company assumes the obligation to keep your information confidential, and will not sell or rent your information to satisfy the marketing purposes of unrelated third parties, and will only share your information with third parties under one of the following circumstances:',
	about_agreement_101: '8.3.1 Get your consent or authorization;',
	about_agreement_102: '8.3.2 In order to provide you with or recommend the services/products of our company’s affiliates, and provide your information to our company’s affiliates for use, you agree to the company’s affiliates via SMS, email, WeChat , QQ, fax, etc. to send you product information, service status notifications, marketing activities or other commercial electronic information;',
	about_agreement_103: '8.3.3 Certain services/products or promotional activities are provided by the company or the company’s affiliated company’s partners or jointly provided by the company, the company’s affiliated company and partners (including but not limited to your approval based on the aforementioned background Binding or using the company’s invitation code for registration or investment), you agree to the company’s use or sharing of your information with the partner;',
	about_agreement_104: '8.3.4 In order to establish a credit system and send your information to credit reporting agencies, you agree and authorize our company to send your bad information to credit reporting agencies without further notice to you;',
	about_agreement_105: '8.3.5 You agree and authorize the company or its affiliates and partners to use or share your information with such organizations in the process of providing information to regulatory agencies and other self-regulatory agencies, for resolving disputes or mediation, etc. . ',
	about_agreement_106: '8.3.6 You agree and authorize the company to share your information with related parties in the process of platform system upgrades or business splits, and the company\'s transfer of rights or obligations to affiliates,partners or other transaction parties;',
	about_agreement_107: '8.3.7 Suppliers that provide independent services and only require necessary information related to the services, such as printing houses, postal companies, etc.;',
	about_agreement_108: '8.3.8 Laws, regulations or regulatory policies, regular or temporary requirements of competent authorities, and other scenarios required to provide you with products or services. ',
	about_agreement_109: '8.4 Protection of your information',
	about_agreement_110: 'The company attaches great importance to the protection of user privacy and will take confidential measures to protect your information in accordance with laws and regulations, except for the following circumstances:',
	about_agreement_111: '8.4.1 Laws, regulations, policies, supervision, industry self-regulatory organizations, etc. otherwise require;',
	about_agreement_112: '8.4.2 This agreement has another agreement;',
	about_agreement_113: '8.4.3 A third party outside the company, force majeure, unexpected events, etc., cause your information to be leaked, misappropriated, sold or otherwise illegally used. ',
	about_agreement_114: '8.5 This clause is independent and should not be affected by the validity or changes of this agreement and other clauses. ',
	about_agreement_115: 'Nine, no guarantee',
	about_agreement_116: '9.1 The platform does not provide any form of promise or guarantee for the services provided to users, regardless of whether such guarantee or promise is express, implied or statutory. ',
	about_agreement_117: '9.2 The quality and content of the services provided by the partner on the platform are the responsibility of the partner. ',
	about_agreement_118: '9.3 The platform does not guarantee continuous, unaffected or safe access to and acceptance of platform services, and the operation of the platform website may be affected by a variety of external factors beyond the control of the platform. ',
	about_agreement_119: 'ten, special statement',
	about_agreement_120: '10.1 The platform does not intervene in transactions between you and other users, and you fully understand and acknowledge this. ',
	about_agreement_121: '10.2 You agree to be solely responsible for the legality of your own actions. You agree that the platform and all affiliated companies and related entities of the platform are not responsible for the legality of the actions of platform users and any results produced. ',
	about_agreement_122: '10.3 You agree and accept these terms of service as if you agree and accept the platform\'s marketing activities in the form of advertising or sending SMS,MMS and email.',
	about_agreement_123: '10.4 Your use of the platform\'s services and the transactions conducted thereby shall comply with all applicable domestic and international laws,decrees,regulations and regulations.',
	about_agreement_124: '11. Compensation and exemption of liability',
	about_agreement_125: '11.1 Regarding any third party, any claim or requirement of any kind and nature arising from or caused by your violation of this agreement or the terms and rules included in this agreement, or your violation of any law or infringement of the rights of a third party , Litigation, loss and damage (including direct or indirect), whether known or unknown (including reasonable attorney’s fees), you agree to deal with the platform and (if applicable) the platform’s parent company, subsidiaries, affiliates, Partners, officers, directors, agents and employees compensate and protect them from harm. ',
	about_agreement_126: '11.2 You agree that due to the particularity of the Internet, the system may not function properly due to related conditions, which may prevent you from using any platform services or be adversely affected. The platform will not be liable to you or the third party for this situation. including but not limited to:',
	about_agreement_127: '(1) The platform system is down for maintenance;',
	about_agreement_128: '(2) Data transmission cannot be carried out due to failure of telecommunication equipment;',
	about_agreement_129: '(3) Service interruption or delay on this platform caused by hacker attacks, network supplier technical adjustments or malfunctions, website upgrades, banking issues, etc.;',
	about_agreement_130: '(4) Due to force majeure factors such as typhoons, earthquakes, tsunamis, floods, power outages, wars, terrorist attacks, etc., the platform system is obstructed and cannot be executed. ',
	about_agreement_131: '12. Protection of intellectual property rights',
	about_agreement_132: '12.1 All content on the platform, including but not limited to works, pictures, files, information, materials, platform architecture, platform screen arrangement, web design, is owned by the platform or other rights holders in accordance with the law, including but not Limited to trademark rights, patent rights, copyrights, trade secrets, etc. ',
	about_agreement_133: '12.2 Without the written consent of the platform or other right holders, no one may download, use, modify, copy, publicly disseminate, change, distribute, issue or publicly publish the platform programs or content without the written consent of the platform or other right holders; System access to directly or indirectly create or edit collections, compilations, databases or names and addresses (regardless of whether through Robots, Spiders, automatic instruments or manual operations); no resale or commercial use of platform content; no collection and use of products Catalogues, descriptions and prices; do not use frames or use frame techniques to take the platform or its affiliates’ trademarks, logos or other proprietary information (including images, text, web design or form) as your own; do not use Meta Tags or any Other "hidden text" methods use the names and trademarks of the platform or its affiliates. ',
	about_agreement_134: 'Thirteen, no agency relationship',
	about_agreement_135: 'Users and platforms are independent contracting parties, and this agreement is not intended to establish or create any agency, partnership, joint venture, employee-employer or franchise relationship. The platform also does not make explicit or tacit recommendations, promises or guarantees for any users and their online transactions. The above properties will not be changed for any reason. ',
	about_agreement_136: 'Fourteen, notice',
	about_agreement_137: 'For your notice and any other agreements, notices or other notices about your use of the platform\'s account and services,you agree that the platform can use platform announcements, site letters,emails,mobile phone text messages,	ins,facebook,wireless communication Electronic means such as devices or physical means such as mailing,such notices are deemed to have been delivered to the recipient on the day of sending(if you send you notices by mail, the notices will be based on the contact address you keep on the platform The third calendar day after delivery is deemed to be served).Due to reasons not attributable to the platform(including but not limited to inaccurate or invalid e - mail address,mobile phone number, contact address, etc., information transmission failure, etc.),you did not receive such notice on the date when the foregoing notice is deemed to have been delivered Yes,the platform does not assume any responsibility.',
	about_agreement_138: '15. Entry into force, modification, supplement and termination of the agreement',
	about_agreement_139: '15.1 During the execution of this agreement, the platform may modify this agreement according to the situation. Once the content of this agreement changes, you will be notified through platform announcements, and such changes will take effect from the date of announcement. ',
	about_agreement_140: '15.2 If you do not accept such modifications and additions, you should immediately stop using the platform\'s services,and the platform has the right to terminate your user qualifications.If you continue to use the platform services,it is deemed that you have accepted the platform\'s modifications to this agreement, and you should follow the modified agreement. ',
	about_agreement_141: '15.3 This agreement will take effect when your application for registration as a platform user is approved. ',
	about_agreement_142: '15.4 This agreement terminates on the date your application to cancel your user account is approved by the platform, or the platform terminates your user qualifications in accordance with this agreement and the documents, terms and conditions included or mentioned in this agreement . ',
	about_agreement_143: '16. Interpretation of terms, application of law and dispute settlement',
	about_agreement_144: '16.1 The validity of this agreement and its amendments, the performance of all aspects related to the validity of this agreement and its amendments are subject to the jurisdiction of the United States and other international laws. ',
	about_agreement_145: '16.2 Any disputes or disputes between you and the platform caused by this agreement should first be settled through friendly negotiation. If the negotiation cannot be resolved, it should be submitted to the court with jurisdiction in the place where the platform is located. ',
	about_agreement_146: '16.3 The provisions of this agreement are severable. If any provision of this agreement is ruled to be invalid or unenforceable, in this case, the other provisions of this agreement are still fully valid and binding. ',
	about_agreement_147: '16.4 The failure of the platform to take action on your or other party’s breach of contract does not mean that the platform waives the right to take action on subsequent or similar breaches of contract. ',
	about_agreement_148: '16.5 This agreement may be adjusted according to the new national policies and the improvement of relevant laws. The final interpretation right belongs to the FIEX operator platform. ',


	// 账户管理
	account_wallet_addr: 'addr:',
	account_wallet_name: 'Wallet name',
	account_export_mnemonic: 'Export mnemonic words',
	account_export_private_key: 'Export private key',
	account_exit_wallet: 'Exit the wallet',
	account_please_input_wallet_name: 'Please enter the wallet name',
	account_wallet_is_empty: 'Wallet name cannot be empty',
	account_wallet_length_is_error: 'Wallet name is set to within 10 characters',
	account_tradepassword_is_error: 'Trading password is incorrect',
	account_export_success: 'Export successful',
	account_export_tips_1: 'Please carefully copy and keep it safe, and do not disclose your private key',
	account_export_tips_2: 'The wallet server does not keep the user\'s private key,and it cannot be retrieved if it is lost ',
	account_wallet_address: 'Wallet address',
	account_private_key: 'Private key',
	account_mnemonic: 'mnemonic phrase',

	// activate
	active_invite: 'Invite to activate',
	active_input_other_addr: 'Please enter the address of the other party',
	active_other_addr: 'other address',
	active_must_use: 'Activation requires consumption',
	active_invite_success: 'Activation successful',

	// mine
	mine_yijh: 'Activated',
	mine_weijh: 'Not activated',
	mine_send: 'Post transaction',
	mine_shequ: 'My Community',
	mine_service: 'Online customer service',
	mine_action: 'Operation Tutorial',
	mine_safe: 'Safety Center',
	mine_language: 'Language switch',
	mine_account: 'Account Management',
	mine_explorer: 'Block Explorer',
	mine_open: 'Open source address',
	mine_share: 'Share APP',
	mine_version: 'version number',


	// announcement
	announcement_title: 'Announcement',
	announcement_title_details: 'Announcement details',


	// assets
	assets_total: 'Total account assets converted',
	assets_button_1: 'Withdrawal',
	assets_button_2: 'Deposit coins',
	assets_button_3: 'Transfer',
	assets_tabs_1: 'coin currency',
	assets_tabs_1_total: 'Total currency assets converted',
	assets_tabs_2: 'Contract',
	assets_tabs_2_total: 'Total legal currency assets converted',
	assets_tabs_3: 'Pool',
	assets_tabs_3_total: 'Total assets of the mining pool converted',
	assets_airdrop_quota: 'Airdrop quota:',
	assets_input: 'into:',
	assets_out: 'out:',
	assets_select_trade: 'Select currency',
	assets_transfer_num: 'transfer amount',
	assets_can_use: 'Available:',


	assets_tabs_5_button_1: 'Node equity',
	assets_tabs_5_button_2: 'Contract return',
	assets_tabs_5_header_1: 'Total return',
	assets_tabs_5_header_2: 'Returned',
	assets_detail_record: 'Financial records',
	assets_detail_title: 'Record details',
	assets_detail_1: 'Type',
	assets_detail_2: 'Buy',
	assets_detail_3: 'State',
	assets_detail_4: 'completed',
	assets_detail_5: 'Time',


	// Collection
	collection_title: 'AFIL Collection',
	collection_wallet_addr: 'wallet address',
	collection_scan: 'scan',
	collection_record_detail: 'Record details',
	collection_out_afil: 'transfer to AFIL',
	collection_out_addr: 'transfer out address',
	collection_receive_addr: 'receive address',
	collection_finish: 'Destroy',
	collection_kuaigao: '',
	collection_type_1: 'transfer',
	collection_type_2: 'Activate account',
	collection_type_3: 'Mining revenue',
	collection_type_4: 'Withdrawal',
	collection_account_record: 'account record',
	collection_status_1: 'Unconfirmed',
	collection_status_2: 'Confirmed',

	// community
	shequ_title_1: 'Activate miner',
	shequ_title_2: 'Shared voting',
	shequ_text_1: 'Activation number',
	shequ_text_2: 'Total number of devices',
	shequ_text_3: 'Mining Pool Level',
	shequ_text_4: 'Number of people invited',
	shequ_text_5: 'Number of people in the community',
	shequ_text_6: 'Number of valid votes',
	shequ_text_7: 'addr',
	shequ_text_8: 'Number of devices',
	shequ_text_9: 'people',
	shequ_text_10: 'Team size',


	// mining pool
	pool_title: 'Pool',
	pool_min_chi: 'min',
	pool_day_income: 'daily',
	pool_total_income: 'cumulative',
	pool_chi_or_tui: 'holding/promotional',
	pool_detail: 'Mining Pool Details',
	pool_income: 'Mining Pool Income',
	pool_chi_calculate: 'Coin holding power',
	pool_tg_calculate: 'Promotional calculation power',
	pool_miner_detail: 'Miner details',
	pool_week_income: 'Recent week income',
	pool_chi_rate: 'coin holding rate of return',
	pool_tg_total_calculate: 'Promotion total computing power',
	pool_chibi: 'Coin holding',
	pool_income_record: 'income record',
	pool_chi_income: 'coin holding income',
	pool_tg_income: 'Promotional income',


	// mnemonic
	mnemonic_i_read: 'I have read and agreed',
	mnemonic_user_agreement: 'User Agreement',
	mnemonic_create_addr: 'Create address',
	mnemonic_export_addr: 'import address',
	mnemonic_agree_first: 'Please agree to the user agreement first',
	mnemonic_backup_succ: 'Backup successful',
	mnemonic_create_succ: 'Create address successfully',
	mnemonic_save_your: 'Please keep your mnemonic words properly',
	mnemonic_not_forget: 'Do not lose or disclose to others, so as not to cause property damage',
	mnemonic_set_your_name_pwd: 'Set your wallet name and transaction password',
	mnemonic_wallet_name: 'wallet name',
	mnemonic_input_wallet_name: 'Please enter your wallet name',
	mnemonic_input_name_length_error: 'Wallet name is set to within 10 characters',
	mnemonic_input_number_and_word: 'Please enter a number plus letter password',
	mnemonic_input_safe_pwd: 'Please enter a safe password',
	mnemonic_two_pwd_not: 'The two password entries are inconsistent',
	mnemonic_input_tradepassword: 'Please enter your trading password',
	mnemonic_again_tradepassword: 'Reconfirm your trading password',
	mnemonic_confirm_pwd: 'Confirm password',
	mnemonic_test: 'Verify mnemonic words',
	mnemonic_remember_twelve: 'Please select the 12 words you copied down to the top in the correct order',
	mnemonic_sort_error: 'The mnemonic sequence is entered incorrectly',
	mnemonic_write_wallet_and_pwd: 'Please fill in your wallet name and transaction password',
	mnemonic_write: 'Fill in mnemonic words',
	mnemonic_input_tips: 'Please fill in your mnemonic words, English words please separate words by spaces',
	mnemonic_input_your: 'Please enter your mnemonic phrase',
	mnemonic_backup: 'Backup mnemonic phrase',
	mnemonic_remember_next: 'Please remember the order of the following 12 mnemonic words from left to right, we will verify in the next step',


	// News
	news_detail: 'News details',

	// public offering
	offering_title: 'public offering',
	offering_quantity: 'quantity',
	offering_single_price: ' ',
	offering_complate: 'Completed',
	offering_time: 'start - end',
	offering_buy: 'Subscription',
	offering_go_buy: 'Go to subscribe',
	offering_equals_price: 'Price after discount',
	offering_buy_quantity: 'Subscription quantity',
	offering_use_quantity: 'Available quantity',
	offering_equals: 'equals',
	offering_input_your_tradepassword: 'Please enter your trading password',
	offering_not_open: 'not open',
	offering_processing: 'in progress',
	offering_finish: 'finished',
	offering_buy_quantity: 'Please enter the subscription quantity',
	offering_input_tradepassword: 'Please enter the transaction password',
	offering_tradepassword_error: 'Trading password is incorrect',
	offering_buy_success: 'Subscription is successful',
	offering_record: 'public offering record',
	offering_price: 'public offering price',
	offering_money: 'public offering amount',
	offering_buy_time: 'Subscription time',


	// other
	other_title: 'Other',
	other_text_1: 'Vote',
	other_text_2: 'Invite',
	other_text_3: 'Activate',
	other_text_4: 'Receipt',
	other_text_5: 'transfer',
	other_text_6: 'offering',
	other_text_7: 'Contract',
	other_text_8: 'Pool',
	other_text_9: 'Mall',
	other_text_10: 'Game',
	other_text_11: 'Education',
	other_text_12: 'Charity',
	other_text_13: 'Exchange',


	// Quotes
	quotes_title: 'quotes',
	quotes_header_1: 'Name',
	quotes_header_2: 'Latest price',
	quotes_header_3: 'Rise and fall',
	quotes_24: '24H amount',

	// Security center

	safe_title: 'Security Center',
	safe_auth: 'Real-name authentication',
	safe_tradepassword: 'Trade password',
	safe_account: 'Receiving account',
	safe_toModify: 'To modify',
	safe_status_1: 'Not certified',
	safe_status_2: 'Authentication in progress',
	safe_status_3: 'Authenticated',
	safe_status_4: 'Authentication failed',


	safe_auth_title: 'Identity Authentication',
	safe_auth_primary_text_1: 'Real name',
	safe_auth_primary_text_2: 'Certificate Number',
	safe_auth_primary_text_3: 'Please upload the front photo of the ID card',
	safe_auth_primary_text_4: 'Please upload a photo of the back of the ID card',
	safe_auth_primary_text_5: 'Please upload a photo of a handheld ID card',
	safe_auth_primary_btn: 'Submit for review',
	safe_auth_primary_toast_1: 'Please enter your real name',
	safe_auth_primary_toast_2: 'Please enter your ID number',
	safe_auth_primary_toast_3: 'Please upload a front photo of your ID card',
	safe_auth_primary_toast_4: 'Please upload the reverse photo of the ID card',
	safe_auth_primary_toast_5: 'Please upload a hand-held ID photo',
	safe_auth_primary_toast_6: 'Submission is successful, please wait for review',

	// payment method
	safe_skfs_title: 'Payment method',
	safe_skfs_bankcard: 'UnionPay Collection Code',
	safe_skfs_alipay: 'Alipay payment code',
	safe_skfs_wechat: 'WeChat Collection Code',
	safe_skfs_yibd: 'Bounded',
	safe_skfs_weibd: 'unbound',

	safe_confirm: 'Confirm binding',
	safe_binding: 'Binding',
	safe_bind_succ: 'bind successfully',


	//Bank card settings
	safe_bank_title: 'UnionPay',
	safe_bank_name: 'Name',
	safe_bank_bankCardId: 'CardId',
	safe_bank_bankName: 'Account Bank',
	safe_bank_bankAddress: 'open addr',
	safe_bank_toast_1: 'Please enter your real name',
	safe_bank_toast_2: 'Please enter the bank card number',
	safe_bank_toast_3: 'Please enter the bank card opening bank',
	safe_bank_toast_4: 'Please enter the bank card account opening address',


	//Alipay Settings
	safe_alipay_title: 'Alipay',
	safe_alipay_name: 'Real name',
	safe_alipay_cardId: 'Alipay id',
	safe_alipay_toast_1: 'Please upload the payment code',
	safe_alipay_toast_2: 'Please enter your Alipay account real-name authentication name',
	safe_alipay_toast_3: 'Please enter Alipay account number',

	//WeChat settings
	safe_wechat_title: 'Wechat',
	safe_wechat_name: 'Real name',
	safe_wechat_cardId: 'Wechat id',
	safe_wechat_toast_1: 'Please upload the payment code',
	safe_wechat_toast_2: 'Please enter the name of the WeChat account for real-name verification',
	safe_wechat_toast_3: 'Please enter the WeChat collection account that needs to be bound',


	// Modify transaction password
	safe_xgjymm_title: 'Modify transaction password',
	safe_xgjymm_note: 'Please reset your transaction password',
	safe_xgjymm_text_1: 'Original transaction password',
	safe_xgjymm_text_2: 'New transaction password',
	safe_xgjymm_text_3: 'Confirm new transaction password',
	safe_xgjymm_text_4: 'Please enter the new password again',
	safe_xgjymm_text_5: 'Set new transaction password',
	safe_xgjymm_text_6: 'Current transaction password',
	safe_xgjymm_modify_succ: 'Modified successfully',
	safe_xgjymm_modify_ing: 'Modifying',
	safe_xgjymm_modify: 'Modify',
	safe_xgjymm_toast_1: 'The two entered passwords are not consistent',

	// OTC
	otc_title: 'Transaction',
	otc_tabs_1: 'I want to buy',
	otc_tabs_2: 'I want to sell',
	otc_message_1: 'The transaction cannot be withdrawn within 24 hours after the purchase, and other transactions will not be affected',
	otc_text_1: 'Tradable quantity',
	otc_text_2: 'Actual payment',
	otc_text_3: 'Actual payment',
	otc_text_4: 'Place an order',
	otc_text_5: 'Automatically cancel afterwards',
	otc_text_6: 'Quantity',
	otc_text_7: 'Limited',
	otc_text_8: 'Single',
	otc_text_9: 'Unit price',
	otc_text_10: 'Purchase',
	otc_text_11: 'Sale',
	otc_text_12: 'Limit',
	otc_loading: 'List pulling',
	otc_s_cancel: 'Automatically cancel after s',
	otc_60_cancel: 'Automatically cancel after 60s',
	otc_toast_1: 'Please enter the purchase quantity',
	otc_toast_2: 'Order received successfully',

	otc_record_title: 'Transaction Record',
	otc_record_status_1: 'Incomplete',
	otc_record_status_2: 'Completed',
	otc_record_status_3: 'Cancelled',
	otc_record_status_4: 'Appeal',
	otc_record_buy: 'Buy',
	otc_record_sell: 'Sell',
	otc_record_label_1: 'Total amount',
	otc_record_label_2: 'number',
	otc_record_list_1: 'Pending orders',
	otc_record_list_2: 'Pending payment',
	otc_record_list_3: 'Pending payment',
	otc_record_list_4: 'Completed',
	otc_record_list_5: 'Canceled',
	otc_record_list_6: 'Appealing',
	otc_record_list_7: 'Appeal successful',
	otc_record_list_8: 'Appeal failed',

	otc_appeal_title: 'Order Appeal',
	otc_appeal_placeholder: 'Please enter your reason for appeal',
	otc_appeal_btn: 'OK to submit',
	otc_appeal_label: 'Please select an appeal category',
	otc_appeal_list_1: 'Payment-the user has paid, but the merchant does not confirm the receipt',
	otc_appeal_list_2: 'Sell order-when not paid, the merchant clicks on paid',
	otc_appeal_list_3: 'Sell order-the merchant has paid, but the payment amount is wrong',
	otc_appeal_toast_1: 'Please enter your reason for appeal',

	otc_details_lable_1: 'Order number',
	otc_details_lable_2: 'Seller\'s real name information ',
	otc_details_lable_3: 'Buyer\'s real - name information ',
	otc_details_lable_4: 'Order time',
	otc_details_lable_5: 'Payment Information',
	otc_details_lable_6: 'Payment Information',
	otc_details_lable_7: 'Real name',
	otc_details_lable_8: 'Bank card number',
	otc_details_lable_9: 'Bank opening bank',
	otc_details_lable_11: 'Alipay name',
	otc_details_lable_12: 'Alipay account',
	otc_details_lable_13: 'Alipay payment code',
	otc_details_lable_14: 'WeChat name',
	otc_details_lable_15: 'WeChat account',
	otc_details_lable_16: 'WeChat payment code',
	otc_details_tips_1: 'Transaction reminder',
	otc_details_tips_2: 'If the buyer does not transfer payment to you, please be sure to click the "I want to appeal" button before the end of the payment countdown, otherwise the order will be automatically confirmed and property may be lost. ',
	otc_details_tips_3: 'The transaction has been completed and the fiat currency has been issued to your account',
	otc_details_btn_1: 'I have paid',
	otc_details_btn_2: 'Confirm payment',
	otc_details_btn_3: 'Confirm order',
	otc_details_btn_4: 'Cancel',
	otc_details_btn_5: 'Cancel appeal',
	otc_details_btn_6: 'Appeal',
	otc_details_phone_1: 'Call out to this number soon',
	otc_details_phone_2: 'Call out now',
	otc_details_select_label: 'Select payment method',
	otc_details_toast_1: 'Please wait for the seller to review the payment',
	otc_details_toast_2: 'Confirm that the payment is successful',
	otc_details_toast_3: 'Confirm success',
	otc_details_toast_4: 'Cancellation successful',
	otc_details_toast_5: 'Revocation successfully succeeded',
	otc_payment_bank: 'UnionPay',
	otc_payment_alipay: 'Alipay',
	otc_payment_wechat: 'WeChat',
	otc_time_m: 'minutes',
	otc_time_s: 'seconds',


	// OTC advertises
	otc_publish_ad: 'Publish an ad',
	otc_publish_tab_1: 'I want to buy',
	otc_publish_tab_2: 'I want to sell',
	otc_publish_text: 'Choose transaction currency',
	otc_publish_text_1: 'price',
	otc_publish_text_2: 'Quantity',
	otc_publish_text_3: 'min',
	otc_publish_text_4: 'max',
	otc_publish_text_5: 'Payment method',
	otc_publish_text_6: 'transaction password',
	otc_publish_pay_1: 'UnionPay',
	otc_publish_pay_2: 'Alipay',
	otc_publish_pay_3: 'WeChat',
	otc_publish_input_1: 'Please enter the price',
	otc_publish_input_2: 'Please enter the quantity',
	otc_publish_input_3: 'Please enter the minimum single transaction amount',
	otc_publish_input_4: 'Please enter the maximum single transaction amount',
	otc_publish_input_5: 'The payment method is not set',
	otc_publish_input_6: 'Please enter the transaction password',
	otc_publish_tips_1: 'Notes',
	otc_publish_tips_2: 'Please be sure to receive the payment before confirming the payment',
	otc_publish_tips_3: 'Please verify the source of funds and transfer notes to avoid bank cards being frozen by the bank',
	otc_publish_button: 'publish now',
	otc_publish_code: 'Verification code',
	otc_publish_reset: 'Reacquire',
	otc_publish_toast_1: 'Please enter the minimum amount',
	otc_publish_toast_2: 'Please enter the maximum limit',
	otc_publish_toast_3: 'The maximum limit cannot be less than the minimum limit',
	otc_publish_toast_4: 'The minimum limit cannot be greater than the required quantity',
	otc_publish_toast_5: 'The maximum limit cannot be greater than the required quantity',
	otc_publish_toast_6: 'published successfully',
	otc_publish_record: 'publish record',
	otc_publish_record_cancel: 'Cancel',
	otc_publish_record_price: 'Price',
	otc_publish_record_quantity: 'quantity',
	otc_publish_record_sjcj: 'Actual deal',
	otc_publish_record_status: 'Status',
	otc_publish_record_toast: 'Revocation successful',


	// transfer
	convert_title: 'Transfer',
	convert_text: 'Select currency',
	convert_text_1: 'Receiving address',
	convert_text_2: 'quantity',
	convert_text_3: 'Available quantity',
	convert_text_4: 'Transaction password',
	convert_text_5: 'Handling fee',
	convert_text_6: 'OK',
	convert_input_1: 'Enter the recipient\'s receiving address ',
	convert_input_2: 'Please enter the transfer amount',
	convert_input_3: 'All',
	convert_input_4: 'Please enter your trading password',
	convert_toast_1: 'The receiving address cannot be empty',
	convert_toast_2: 'The transfer amount cannot be empty',
	convert_toast_3: 'Transaction password cannot be empty',
	convert_toast_4: 'The available quantity is insufficient',
	convert_toast_5: 'Transfer is successful',

	// vote
	vote_title_1: 'Share vote',
	vote_title_2: 'Real-time voting',
	vote_item_1: 'in progress',
	vote_item_2: 'All',
	vote_item_3: 'Ended',
	vote_text_1: 'No data yet',
	vote_text_2: 'Current: first',
	vote_text_3: 'period',
	vote_text_4: 'Profit per period',
	vote_text_5: 'vote amount',
	vote_text_6: 'Completed',
	vote_text_7: 'Total vote',
	vote_text_8: 'start - end',
	vote_text_9: 'Participate in voting',
	vote_text_10: 'Subscribe',
	vote_text_11: 'Price',
	vote_text_12: 'Subscription quantity',
	vote_text_13: 'Limit',
	vote_text_14: 'Actual payment',
	vote_text_15: 'transaction password',
	vote_text_16: 'Please enter your trading password',
	vote_status_1: 'not open',
	vote_status_2: 'in progress',
	vote_status_3: 'Ended',
	vote_toast_1: 'Please enter the subscription quantity',
	vote_toast_2: 'Please enter the transaction password',
	vote_toast_3: 'Trading password is incorrect',
	vote_toast_4: 'Subscription is successful',
	vote_record: 'Vote Record',
	vote_record_list_1: 'unit price',
	vote_record_list_2: 'vote amount',
	vote_record_list_3: 'Actual number of transactions',
	vote_record_list_4: 'Subscription time',



	// APP information prompt
	app_w1: 'Update prompt',
	app_w2: 'New version detected',
	app_w3: 'Your version is',
	app_w4: 'You are not logged in',
	app_w5: 'Please try again later',

	// login page
	login_username: 'Account',
	login_username_placeholder: 'Please enter the registered mobile phone number/email',
	login_password: 'Password',
	login_password_placeholder: 'Please enter your password',
	login_forget: 'Forgot password',
	login_login: 'Login',
	login_register: 'Create account',
	login_toast_loggingIn: 'Logging in',
	login_toast_loginSuccess: 'Login successful',
	login_drag_1: 'Drag the slider to verify',
	login_drag_2: 'Verification passed',
	login_drag_3: 'Authentication failed',

	// Registration page
	register_phone: 'Mobile phone registration',
	register_email: 'email registration',
	register_username: 'Account',
	register_username_phone_placeholder: 'Please enter your phone number',
	register_username_email_placeholder: 'Please enter your email',
	register_code: 'Verification code',
	register_code_placeholder: 'Please enter the verification code',
	register_sendCode: 'Send verification code',
	register_sending: 'Sending',
	register_sendSuccess: 'Send success',
	register_next: 'Next',
	register_loginPassword: 'Login Password',
	register_loginPassword_placeholder: 'Please set a login password',
	register_tradePassword: 'Trade Password',
	register_tradePassword_placeholder: 'Please set a trading password',
	register_inviteCode: 'Invite Code',
	register_inviteCode_placeholder: 'Please enter the invitation code',
	register_register: 'Register',
	register_registerSuccess: 'Registered successfully',

	// Forgot password page
	forget_forget: 'Forget Password',
	forget_username: 'Account',
	forget_username_placeholder: 'Please enter the registered mobile phone number/email',
	forget_code: 'Verification code',
	forget_code_placeholder: 'Please enter the verification code',
	forget_sendCode: 'Send verification code',
	forget_sending: 'Sending',
	forget_sendSuccess: 'Send success',
	forget_next: 'Next',
	forget_resetPassword: 'Reset Password',
	forget_message: 'Your account will use the new password to log in after the password is reset',
	forget_newPassword: 'New Password',
	forget_newPassword_placeholder: 'Please enter your new password',
	forget_againPassword: 'Confirm password',
	forget_againPassword_placeholder: 'Please confirm your new password',
	forget_modify: 'Modify',
	forget_modifySuccess: 'Modification successful',

	// Home
	index_navigationBox_item_1: 'Vote',
	index_navigationBox_item_2: 'Invite',
	index_navigationBox_item_3: 'Activate',
	index_navigationBox_item_4: 'Collection',
	index_navigationBox_item_5: 'Transfer',
	index_navigationBox_item_6: 'Offering',
	index_navigationBox_item_7: 'Contract',
	index_navigationBox_item_8: 'Other',
	index_tabs_1: 'Increase list',
	index_tabs_2: 'Declining list',
	index_tabs_3: 'Deal list',
	index_info: 'Information',
	index_menu_item_1: 'AFIL Mine Pool',
	index_menu_item_2: 'Shared voting',
	index_menu_item_3: 'Real-time voting',
	index_menu_item_4: 'Insurance Fund',
	index_chengjiu: 'Achievement of tomorrow\'s star ',


	// currency transaction
	exchange_title: 'Currency',
	exchange_tabs_1: 'Current delegate',
	exchange_tabs_2: 'History',
	exchange_tabs_3: 'Transaction History',
	exchange_menu_title: 'coin list',
	exchange_toast_1: 'Please log in before trading',
	exchange_toast_2: 'Price cannot be less than 0',
	exchange_toast_3: 'The quantity cannot be less than 0',
	exchange_title_1: 'Fiat currency',
	exchange_record: 'Record',
	exchange_record_tab_1: 'Current',
	exchange_record_tab_2: 'History',
	exchange_record_tab_3: 'Record',
	exchange_record_text_1: 'No record yet',
	exchange_record_text_2: 'Price',
	exchange_record_text_3: 'quantity',
	exchange_record_text_4: 'Actual',
	exchange_record_cancel: 'Cancel order',
	exchange_record_toast: 'Order cancelled successfully',
	

	// contract transaction
	contract_title_1: 'Contract transaction',
	contract_title_2: 'Insurance contract',
	contract_currency_unit: 'Perpetual',
	contract_header_btn_1: 'Open position',
	contract_header_btn_2: 'Close position',
	contract_header_btn_3: 'Position',
	contract_button_1: 'Buy open long',
	contract_button_2: 'Buy close short',
	contract_button_3: 'Sell open short',
	contract_button_4: 'Sell flat and long',
	contract_button_5: 'Close position with one click',
	contract_button_6: 'Take Profit Stop Loss',
	contract_trade_unit: 'hand',
	contract_tabs_1: 'Current positions',
	contract_tabs_2: 'Plan Entrusted',
	contract_tabs_3: 'Current delegate',
	contract_tabs_4: 'historical commission',
	contract_tabs_5: 'Close position record',
	contract_label_1: 'Average transaction price',
	contract_label_2: 'Earnings',
	contract_label_3: 'Estimated strong parity',
	contract_label_4: 'Yield',
	contract_label_5: 'Take Profit Price',
	contract_label_6: 'Stop Loss Price',
	contract_label_7: 'Open interest',
	contract_label_8: 'Margin',
	contract_label_9: 'Amountable to be flat',
	contract_label_10: 'Entrusted amount',
	contract_label_11: 'Order price',
	contract_label_12: 'Margin',
	contract_label_13: 'Volume',
	contract_label_14: 'Contract price',
	contract_label_15: 'Handling fee',
	contract_label_16: 'Delegation method',
	contract_label_17: 'Quantity',
	contract_label_18: 'Required Margin',
	contract_label_19: 'Insurance required',
	contract_label_20: 'Average opening price',
	contract_label_21: 'Take Profit',
	contract_label_22: 'Stop Loss',
	contract_label_23: 'Estimated income',
	contract_label_24: 'Opening price',
	contract_label_25: 'Close price',
	contract_label_26: 'Earnings',
	contract_label_27: 'Close fee',
	contract_label_28: 'Number of closed positions',
	contract_label_27: 'Yield',
	contract_more_1: 'Contract Settings',
	contract_more_2: 'Calculator',
	contract_prompt_1: 'Warm reminder',
	contract_prompt_2: 'Purchasing this contract requires payment of insurance money to protect transaction risks. ',
	contract_menu_title: 'USDT contract',
	contract_toast_1: 'Please enter the price',
	contract_toast_2: 'Please enter the quantity',
	contract_toast_3: 'Close the order successfully',
	contract_toast_4: 'Price cannot be less than 0',
	contract_toast_5: 'The quantity cannot be less than 0',
	contract_toast_6: 'Please log in before trading',
	contract_set_title: 'Contract Settings',
	contract_set_label_1: 'Limit order confirmation',
	contract_set_label_2: 'Market price order confirmation',
	contract_calculator_title: 'Contract calculator',
	contract_calculator_tabs_1: 'Open long',
	contract_calculator_tabs_2: 'open empty',
	contract_calculator_label_1: 'Leverage multiple',
	contract_calculator_label_2: 'Opening price',
	contract_calculator_label_3: 'Close price',
	contract_calculator_label_4: 'number of open positions',
	contract_calculator_toast_1: 'Please enter the leverage multiple',
	contract_calculator_toast_2: 'Please enter the opening price',
	contract_calculator_toast_3: 'Please enter the closing price',
	contract_calculator_toast_4: 'Please enter the opening quantity',
	contract_calculator_btn: 'Calculation',

	// Deposit
	rechange_title: 'recharge',
	rechange_save_button: 'Save QR code to album',
	rechange_tips_title: 'Warm Tips',
	rechange_tips_info_1: 'Wallet address is forbidden to recharge except for',
	rechange_tips_info_2: 'Anything other than assets other than',
	rechange_tips_info_3: 'Asset recharge will not be retrieved. ',
	rechange_tips_info_4: 'The top-up address will not change frequently, please confirm the address before top-up. ',
	rechange_record: 'Recharge Record',
	rechange_details: 'Recharge details',
	rechange_default_coinType: 'Normal deposit',

	// Withdrawal
	withdrawal_title: 'Withdrawal',
	withdrawal_text_1: 'Enter or long press to paste the address',
	withdrawal_text_2: 'Withdrawal amount',
	withdrawal_text_3: 'Minimum withdrawal amount:',
	withdrawal_text_4: 'All',
	withdrawal_text_5: 'Available quantity:',
	withdrawal_text_6: 'Handling fee',
	withdrawal_text_7: 'Actual arrival',
	withdrawal_text_8: 'Verification code',
	withdrawal_text_9: 'To the phone number',
	withdrawal_text_10: 'Send verification code',
	withdrawal_text_11: 'Please enter the verification code',
	withdrawal_text_12: 'Get verification code',
	withdrawal_text_13: 'Transaction password',
	withdrawal_text_14: 'Please enter the transaction password',
	withdrawal_tips_title: 'Warm Tips',
	withdrawal_tips_1: 'The minimum withdrawal amount is:',
	withdrawal_tips_2: 'In order to ensure the safety of funds, when your account security policy changes, password changes, we will manually review, please be patient. ',
	withdrawal_tips_3: 'Please confirm the safety of your computer and browser to prevent information from being tampered with or leaked. ',
	withdrawal_record: 'Withdrawal record',
	withdrawal_details: 'Withdrawal details',
	withdrawal_details_text_1: 'Submission successful',
	withdrawal_details_text_2: 'The withdrawal has been submitted, please wait for review',
	withdrawal_toast_1: 'Please enter the withdrawal address',
	withdrawal_toast_2: 'Please enter the withdrawal amount',
	withdrawal_toast_3: 'Please enter the verification code',
	withdrawal_toast_4: 'Please enter the transaction password',
	withdrawal_toast_5: 'Withdrawal application successful',
	withdrawal_basic: 'Common withdrawal',
	withdrawal_your: 'your',
	withdrawal_quest: 'The withdrawal has been initiated',
	withdrawal_look: 'View',

	// transfer
	asset_transfer_toast_1: 'Please enter the transfer amount',
	asset_transfer_toast_2: 'Currently available quantity is insufficient',
	asset_transfer_toast_3: 'transfer successful',
	asset_transfer_record_info_1: 'transfer out account',
	asset_transfer_record_info_2: 'transfer to account',
	asset_transfer_type_1: 'coin account',
	asset_transfer_type_2: 'Contract account',
	asset_transfer_type_3: 'fiat currency account',
	asset_transfer_type_4: 'Margin account',
	asset_transfer_select_title: 'Select account',


	// my team
	myTeam_title: 'My Team',
	myTeam_card_title_1: 'Rebate today',
	myTeam_card_title_2: 'Accumulated rebate',
	myTeam_card_title_3: 'Number of people to share',
	myTeam_card_title_4: 'Number of team members',
	myTeam_invitationRecord: 'Invitation Record',
	myTeam_invitationFriend: 'Invite friends',
	myTeam_saveImg: 'Save picture to album',
	myTeam_choosePoster: 'Choose a poster',
	myTeam_record_title: 'Proof of equity',

	// Help Center
	help_title: 'Operation tutorial',
	help_desc: 'I will do my best to help you solve problems',
	help_detail_title: 'Help details',


	// share pictures
	share_img_1: '../../static/share/img-share-01.jpg',
	share_img_2: '../../static/share/img-share-02.jpg',
	share_label_1: 'Invitation code:',
	share_label_2: 'Invite you to join',

	//Set
	set_title: 'Set',
	set_gerzl: 'Personal Information',
	set_shoukfs: 'Payment method',
	set_lang: 'Language selection',
	set_logout: 'Logout',

	// Personal Center
	set_userInfo: 'Personal Information',
	set_avatar: 'avatar',
	set_nickName: 'nickname',
	set_xiugnc: 'Modify nickname',
	set_newnc: 'New nickname',
	set_qsrnxdnc: 'Please enter your new nickname',
	set_shoujh: 'Mobile phone number',
	set_chujrz: 'primary certification',
	set_gaojrz: 'Advanced Certification',
	set_weirz: 'Not authenticated',
	set_renzz: 'certification in progress',
	set_yirz: 'Authenticated',
	set_renzsb: 'Authentication failed',
	set_jiaoyyz: 'Transaction verification',
	set_never: 'Never enter transaction password',
	set_caozcg: 'Operation successful',
	set_shousmm: 'Gesture password',
	set_xiugsjh: 'Modify phone number',
	set_xiugma: 'Modify password',
	set_xiugnc: 'Modify nickname',


	// hint
	toast_input_phone: 'Please enter the phone number/email',
	toast_input_email: 'Please input email',
	toast_input_usernameAll: 'Please enter the registered mobile phone number/email',
	toast_input_verificationCode: 'Please enter the verification code',
	toast_input_password: 'Please enter the login password',
	toast_input_dblpassword: 'Please enter the login password again',
	toast_input_transactionPassword: 'Please enter the transaction password',
	toast_input_invitationCode: 'Please enter the invitation code',
	toast_input_realName: 'Please enter your real name',
	toast_input_idCard: 'Please enter your ID card number',
	toast_input_alipay: 'Please enter Alipay\'s account number ',
	toast_input_wechat: 'Please enter Wechat account number',
	toast_input_payee: 'Please enter your payee',
	toast_input_bankCard: 'Please enter your bank card number',
	toast_input_bankAddress: 'Please enter your bank address',
	toast_username_false: 'Username is incorrect',
	toast_null_password: 'Password cannot be empty',
	toast_null_name: 'Name cannot be empty',
	toast_null_idCard: 'ID card number cannot be empty',
	toast_please_login: 'Please log in first',
	toast_please_more_100_price: 'Please enter a multiple of 100',
	toast_please_more_100_quantity: 'Please enter a multiple of 100',
	toast_please_payCode: 'Please upload your payment code',
	toast_please_carrier: 'Please apply to become a carrier first',
	toast_success_buyNow: 'Buy now successfully',
	toast_success_exchange: 'Successful purchase',
	toast_success_refresh: 'Refresh successful',
	toast_noOpen: 'Not open yet',
	toast_notsmyz: 'You don\'t have real - name authentication yet,go to real - name authentication!',
	toast_password_false: 'Password is incorrect',
	toast_login_doing: 'Login',
	toast_success_send: 'Send successfully',
	toast_dqmmbnwk: 'The current password cannot be empty',
	toast_dqmmgsbzq: 'The current password format is incorrect',
	toast_xmmbnwk: 'The new password cannot be empty',
	toast_xmmgsbzq: 'The format of the new password is incorrect',
	toast_lcmmbyz: 'The two passwords are not consistent',
	toast_dlmmxgcg: 'Login password modified successfully',
	toast_jymmxgcg: 'Transaction password modified successfully',
	toast_qsrwt: 'Please enter your question',
	toast_qsrssyy: 'Please enter the reason for your appeal',
	toast_bcz: 'Save in',
	toast_bccg: 'Save successfully',
	toast_qsrmm: 'Please enter the password',
	toast_liccg: 'Financial management success',
	toast_qxzsl: 'Please select the quantity',
	toast_quedtj: 'OK to submit',
	toast_qsrzs: 'Please enter an integer',
	toast_input_address: 'Please enter or paste in the address',
	toast_input_otherAddress: 'Address alias',
	toast_please_quantity: 'Please enter the quantity',
	toast_chedcg: 'Order cancelled successfully',
	toast_copySuccess: 'Copy successful',
	toast_noLogin: 'You are not logged in',
	toast_verified: 'Verified',

	toast_unsearch_wallet_name: 'Wallet name not found',
	share_desc:'Professional and safe financial asset trading platform',
	account_create_confirm:'OK to create',
	account_create_success:'Created successfully',
	account_import_key_addr:'Please fill in your private key address',
	account_import_open:'Start import',
	account_import_succ:'Import successful',
	g_asset:'asset',
	g_trade:'Trade',
	asset_toast_jscg:'Received successfully',
	
	gateway_text_1:'Add gateway',
	gateway_text_2:'Please select the gateway that needs to be added',
	gateway_text_3:'risk warning',
	gateway_text_4:'NT risk warning',
	gateway_text_5: '1.NT provides a decentralized underlying platform',
	gateway_text_6: '2.NT neither owns the various virtual currencies in the account, nor does it own the trust limit of the gateway',
	gateway_text_7: '3. So the user\'s trust in the gateway must be established on the basis of repeated understanding and trust of the gateway',
	gateway_text_8: '4.NT does not guarantee the credit of the gateway, please choose the gateway carefully',
	gateway_text_9:'Known trust NT risk',

	
	video_content_text_1:'Decentralized financial ecology and distributed storage technology',
	video_content_text_2:'Decentralized on-chain transactions',
	video_content_text_3:'Create address',
	video_content_text_4:'Import address',
	
	
	index_text_1:'Today\'s earnings',
	index_text_2:'Best holding currency',
	index_text_3:'Minimum holding currency',
	index_text_4:'transfer',
	index_text_5:'Mining Pool',
	index_text_6:'Ledger',
	index_text_7:'Receipt',
	index_text_8:'IPFS',
	index_text_9:'DEFI ecology',
	index_text_10:'release',
	index_text_11:'Community',
	index_text_12:'quotes',
	index_text_13:'More',
	index_text_14:'trading pair',
	index_text_15:'Latest price',
	index_text_16:'Rise and fall',
	index_toast_1:'certified',
	index_toast_2:'Please complete the real-name authentication first',
	
	mine_text_1:'Post transaction',
	mine_text_2:'Activate miner',
	mine_text_3:'Share APP',
	mine_text_4:'Account Management',
	mine_text_5:'language switch',
	mine_text_6:'Online customer service',
	mine_text_7:'Operation tutorial',
	mine_text_8:'Security Center',
	mine_text_9:'Official website address',
	mine_text_10:'Block Explorer',
	mine_text_11:'Looking forward',
	mine_text_12:'Open source address',
	mine_text_13:'version number',
	
	mine_status_1:'Not activated',
	mine_status_2:'Activating',
	mine_status_3:'Activated',
}
export default messagesCn
